// Crypto Page Configuration

export const CRYPTO_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'ETF',
            symbols: [
                { s: 'AMEX:BITW', d: 'Bitwise 10 Crypto Index Fund' },
                { s: 'AMEX:GDLC', d: 'Grayscale Digital Large Cap Fund' },
                { s: 'AMEX:CRPT', d: 'First Trust SkyBridge Crypto ETF' },
                { s: 'NASDAQ:DAPP', d: 'VanEck Digital Transformation ETF' },
                { s: 'AMEX:MNRS', d: 'Grayscale Bitcoin Miners ETF' },
                { s: 'NASDAQ:SOLZ', d: 'Volatility Shares Solana ETF' },
                { s: 'NASDAQ:LTCC', d: 'Canary Litecoin ETF' },
                { s: 'NASDAQ:BKCH', d: 'Global X Blockchain ETF' },
                { s: 'AMEX:BLOK', d: 'Amplify Transformational Data ETF' },
                { s: 'AMEX:BITQ', d: 'Bitwise Crypto Innovators ETF' },
                { s: 'AMEX:BLKC', d: 'Invesco Galaxy Blockchain ETF' },
            ],
        },
        {
            title: 'BTC',
            symbols: [
                { s: 'NASDAQ:IBIT', d: 'iShares Bitcoin Trust ETF' },
                { s: 'AMEX:FBTC', d: 'Fidelity Bitcoin Fund' },
                { s: 'AMEX:BITB', d: 'Bitwise Bitcoin ETF' },
                { s: 'AMEX:ARKB', d: 'ARK 21Shares Bitcoin ETF' },
                { s: 'AMEX:HODL', d: 'VanEck Bitcoin Trust' },
                { s: 'AMEX:BTCW', d: 'Grayscale Bitcoin ETF' },
                { s: 'AMEX:BTCO', d: 'Invesco Galaxy Bitcoin ETF' },
                { s: 'AMEX:GBTC', d: 'Grayscale Bitcoin Trust' },
                { s: 'AMEX:BTC', d: 'Grayscale Bitcoin Mini Trust' },
                { s: 'NASDAQ:BRRR', d: 'Valkyrie Bitcoin Fund' },
                { s: 'AMEX:DEFI', d: 'Hashdex Bitcoin ETF' },
                { s: 'NASDAQ:MSTR', d: 'MicroStrategy Incorporated' },
                { s: 'NASDAQ:MARA', d: 'Marathon Digital Holdings' },
                { s: 'NASDAQ:RIOT', d: 'Riot Platforms Inc' },
            ],
        },
        {
            title: 'ETH',
            symbols: [
                { s: 'NASDAQ:ETHA', d: 'iShares Ethereum Trust ETF' },
                { s: 'AMEX:FETH', d: 'Fidelity Ethereum Fund' },
                { s: 'AMEX:ETHW', d: 'Bitwise Ethereum ETF' },
                { s: 'AMEX:ETHE', d: 'Grayscale Ethereum Trust' },
                { s: 'AMEX:ETH', d: 'Grayscale Ethereum Mini Trust' },
                { s: 'AMEX:CETH', d: '21Shares Core Ethereum ETF' },
                { s: 'AMEX:TETH', d: '21Shares Ethereum ETF' },
                { s: 'AMEX:QETH', d: 'Invesco Galaxy Ethereum ETF' },
                { s: 'AMEX:ETHV', d: 'VanEck Ethereum ETF' },
            ],
        },
        {
            title: 'SOL',
            symbols: [
                { s: 'AMEX:BSOL', d: 'Bitwise Solana ETF' },
                { s: 'AMEX:GSOL', d: 'Grayscale Solana ETF' },
                { s: 'AMEX:FSOL', d: 'Fidelity Solana ETF' },
                { s: 'NASDAQ:VSOL', d: 'VanEck Solana ETF' },
                { s: 'CBOE:TSOL', d: '21Shares Solana ETF' },
                { s: 'AMEX:SOEZ', d: 'Franklin Templeton Solana ETF' },
                { s: 'NASDAQ:SOLC', d: 'Canary Solana ETF' },
            ],
        },
        {
            title: 'XRP',
            symbols: [
                { s: 'NASDAQ:XRPC', d: 'Bitwise XRP ETF' },
                { s: 'AMEX:GXRP', d: 'Grayscale XRP Trust' },
                { s: 'AMEX:XRP', d: 'VanEck XRP ETF' },
                { s: 'AMEX:XRPZ', d: 'Franklin Templeton XRP ETF' },
                { s: 'CBOE:TOXR', d: '21Shares XRP ETF' },
            ],
        },
        {
            title: 'Exchanges',
            symbols: [
                { s: 'NASDAQ:COIN', d: 'Coinbase Global Inc' },
                { s: 'NYSE:BLSH', d: 'Bullish' },
                { s: 'NASDAQ:GEMI', d: 'Gemini Space Station' },
                { s: 'NASDAQ:HOOD', d: 'Robinhood Markets Inc' },
                { s: 'NASDAQ:CME', d: 'CME Group Inc' },
                { s: 'NASDAQ:SOFI', d: 'SoFi Technologies Inc' },
            ],
        },
        {
            title: 'Treasury',
            symbols: [
                { s: 'NASDAQ:MSTR', d: 'MicroStrategy' },
                { s: 'NYSE:XYZ', d: 'Universe' },
                { s: 'NASDAQ:FIGR', d: 'Figure Technology Solutions' },
                { s: 'NYSE:GME', d: 'GameStop' },
                { s: 'NYSE:BLSH', d: 'Bullish' },
                { s: 'TSX:GLXY', d: 'Galaxy Digital' },
                { s: 'NASDAQ:MARA', d: 'MARA Holdings' },
                { s: 'NASDAQ:ABTC', d: 'American Bitcoin' },
                { s: 'NASDAQ:ASST', d: 'Asset Entities' },
                { s: 'AMEX:EXOD', d: 'Exodus Movement' },
                { s: 'NASDAQ:SMLR', d: 'Semler Scientific' },
                { s: 'NASDAQ:NAKA', d: 'Nakamoto Holdings' },
                { s: 'NASDAQ:PRE', d: 'Prenetics Global' },
                { s: 'AMEX:KULR', d: 'KULR Technology Group' },
                { s: 'NASDAQ:EMPD', d: 'Emperor Mining' },
                { s: 'NASDAQ:FLD', d: 'Fidelity World' },
                { s: 'NYSE:SQNS', d: 'Sequans Communications' },
                { s: 'NASDAQ:NA', d: 'North America' },
                { s: 'AMEX:DDC', d: 'Data Direct Corp' },
                { s: 'NASDAQ:LVO', d: 'LiveOne' },
                { s: 'NASDAQ:NXTT', d: 'Next Technology' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const CRYPTO_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'Crypto',
    blockSize: 'market_cap_calc',
    blockColor: 'change',
    grouping: 'no_group',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const CRYPTO_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Crypto Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'BITW',
            sourceUrl: 'https://bitwiseinvestments.com/crypto-funds/bitw',
            symbols: [
                { name: 'BINANCE:BTCUSDT', displayName: 'BTC - Bitcoin (75.1%)' },
                { name: 'BINANCE:ETHUSDT', displayName: 'ETH - Ethereum (15.31%)' },
                { name: 'BINANCE:XRPUSDT', displayName: 'XRP - Ripple (4.86%)' },
                { name: 'BINANCE:SOLUSDT', displayName: 'SOL - Solana (2.96%)' },
                { name: 'BINANCE:ADAUSDT', displayName: 'ADA - Cardano (0.57%)' },
                { name: 'BINANCE:LINKUSDT', displayName: 'LINK - Chainlink (0.37%)' },
                { name: 'BINANCE:LTCUSDT', displayName: 'LTC - Litecoin (0.26%)' },
                { name: 'BINANCE:SUIUSDT', displayName: 'SUI - Sui (0.23%)' },
                { name: 'BINANCE:AVAXUSDT', displayName: 'AVAX - Avalanche (0.22%)' },
                { name: 'BINANCE:DOTUSDT', displayName: 'DOT - Polkadot (0.12%)' },
            ],
        },
        {
            name: 'CRPT',
            sourceUrl: 'https://www.ftportfolios.com/Retail/Etf/EtfHoldings.aspx?Ticker=CRPT',
            symbols: [
                { name: 'NASDAQ:MSTR', displayName: 'MSTR - MicroStrategy (18.97%)' },
                { name: 'NASDAQ:COIN', displayName: 'COIN - Coinbase Global (16.23%)' },
                { name: 'TSX:GLXY', displayName: 'GLXY - Galaxy Digital (10.44%)' },
                { name: 'NASDAQ:HOOD', displayName: 'HOOD - Robinhood Markets (8.12%)' },
                { name: 'NASDAQ:IBIT', displayName: 'IBIT - iShares Bitcoin Trust (5.54%)' },
                { name: 'AMEX:FBTC', displayName: 'FBTC - Fidelity Bitcoin Fund (5.15%)' },
                { name: 'AMEX:HODL', displayName: 'HODL - VanEck Bitcoin ETF (4.70%)' },
                { name: 'AMEX:BITB', displayName: 'BITB - Bitwise Bitcoin ETF (4.69%)' },
                { name: 'AMEX:BTCO', displayName: 'BTCO - Invesco Galaxy Bitcoin ETF (4.69%)' },
                { name: 'NASDAQ:IREN', displayName: 'IREN - IREN Ltd (1.97%)' },
                { name: 'NASDAQ:WULF', displayName: 'WULF - TeraWulf (1.96%)' },
                { name: 'NASDAQ:CIFR', displayName: 'CIFR - Cipher Mining (1.80%)' },
                { name: 'NASDAQ:CLSK', displayName: 'CLSK - CleanSpark (0.84%)' },
                { name: 'NASDAQ:FWDI', displayName: 'FWDI - Forward Industries (0.78%)' },
                { name: 'NASDAQ:RIOT', displayName: 'RIOT - Riot Platforms (0.71%)' },
                { name: 'NASDAQ:HIVE', displayName: 'HIVE - HIVE Digital Technologies (0.60%)' },
                { name: 'NASDAQ:MARA', displayName: 'MARA - MARA Holdings (0.45%)' },
                { name: 'NASDAQ:BTDR', displayName: 'BTDR - Bitdeer Technologies (0.37%)' },
                { name: 'NASDAQ:DJT', displayName: 'DJT - Trump Media & Technology (0.22%)' },
            ],
        },
        {
            name: 'DAPP',
            sourceUrl: 'https://www.vaneck.com/us/en/investments/digital-transformation-etf-dapp/overview/',
            symbols: [
                { name: 'NASDAQ:IREN', displayName: 'IREN - Iren Ltd (7.98%)' },
                { name: 'AMEX:BMNR', displayName: 'BMNR - Bitmine Immersion Technologies (7.30%)' },
                { name: 'NASDAQ:COIN', displayName: 'COIN - Coinbase Global (6.31%)' },
                { name: 'NASDAQ:APLD', displayName: 'APLD - Applied Digital (6.27%)' },
                { name: 'NASDAQ:CLSK', displayName: 'CLSK - Cleanspark (6.24%)' },
                { name: 'NASDAQ:CIFR', displayName: 'CIFR - Cipher Mining (6.21%)' },
                { name: 'NYSE:CRCL', displayName: 'CRCL - Circle Internet Group (5.63%)' },
                { name: 'NYSE:SQ', displayName: 'SQ - Block (5.23%)' },
                { name: 'NASDAQ:HUT', displayName: 'HUT - Hut 8 (4.99%)' },
                { name: 'NASDAQ:MSTR', displayName: 'MSTR - MicroStrategy (4.98%)' },
                { name: 'NASDAQ:RIOT', displayName: 'RIOT - Riot Platforms (4.83%)' },
                { name: 'NASDAQ:GLXY', displayName: 'GLXY - Galaxy Digital (4.82%)' },
                { name: 'NASDAQ:BTDR', displayName: 'BTDR - Bitdeer Technologies (4.09%)' },
                { name: 'NASDAQ:WULF', displayName: 'WULF - Terawulf (4.01%)' },
                { name: 'NASDAQ:CORZ', displayName: 'CORZ - Core Scientific (3.85%)' },
                { name: 'NASDAQ:MARA', displayName: 'MARA - MARA Holdings (3.82%)' },
                { name: 'NYSE:BLSH', displayName: 'BLSH - Bullish (3.31%)' },
                { name: 'NASDAQ:BTBT', displayName: 'BTBT - Bit Digital (2.52%)' },
                { name: 'NASDAQ:FIGR', displayName: 'FIGR - Figure Technology Solutions (2.51%)' },
                { name: 'OTC:BCTCF', displayName: 'BCTCF - OSL Group (2.31%)' },
                { name: 'OTC:MTPLF', displayName: 'MTPLF - Metaplanet (2.05%)' },
                { name: 'NASDAQ:GEMI', displayName: 'GEMI - Gemini Space Station (0.67%)' },
                { name: 'NASDAQ:OWLS', displayName: 'OWLS - Obook Holdings (0.10%)' },
            ],
        },
        {
            name: 'BLOK',
            sourceUrl: 'https://stockanalysis.com/etf/blok/holdings/',
            symbols: [
                { name: 'NASDAQ:HOOD', displayName: 'HOOD - Robinhood Markets (4.64%)' },
                { name: 'TSX:GLXY', displayName: 'GLXY - Galaxy Digital (4.26%)' },
                { name: 'NASDAQ:CIFR', displayName: 'CIFR - Cipher Mining (4.22%)' },
                { name: 'NASDAQ:HUT', displayName: 'HUT - Hut 8 (4.21%)' },
                { name: 'NASDAQ:CLSK', displayName: 'CLSK - CleanSpark (3.83%)' },
                { name: 'NASDAQ:WULF', displayName: 'WULF - TeraWulf (3.43%)' },
                { name: 'NASDAQ:COIN', displayName: 'COIN - Coinbase Global (3.33%)' },
                { name: 'NYSE:IBM', displayName: 'IBM - International Business Machines (3.25%)' },
                { name: 'NYSE:NU', displayName: 'NU - Nu Holdings (3.15%)' },
                { name: 'NASDAQ:PYPL', displayName: 'PYPL - PayPal Holdings (2.82%)' },
                { name: 'AMEX:FBTC', displayName: 'FBTC - Fidelity Wise Origin Bitcoin Fund (2.47%)' },
                { name: 'NASDAQ:CORZ', displayName: 'CORZ - Core Scientific (2.45%)' },
                { name: 'NASDAQ:OPRA', displayName: 'OPRA - Opera Limited (2.41%)' },
                { name: 'NYSE:RBLX', displayName: 'RBLX - Roblox (2.36%)' },
                { name: 'NYSE:BLK', displayName: 'BLK - BlackRock (2.31%)' },
                { name: 'NASDAQ:FIGR', displayName: 'FIGR - Figure Technology Solutions (2.16%)' },
                { name: 'NASDAQ:CME', displayName: 'CME - CME Group (2.12%)' },
                { name: 'NYSE:SQ', displayName: 'SQ - Block (2.07%)' },
                { name: 'AMEX:BITB', displayName: 'BITB - Bitwise Bitcoin ETF (1.99%)' },
                { name: 'NASDAQ:IBIT', displayName: 'IBIT - iShares Bitcoin Trust ETF (1.99%)' },
                { name: 'NASDAQ:MELI', displayName: 'MELI - MercadoLibre (1.90%)' },
            ],
        },
        {
            name: 'RWA',
            sourceUrl: 'https://www.coingecko.com/en/categories/xstocks-ecosystem',
            symbols: [
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon' },
                { name: 'NASDAQ:ASML', displayName: 'ASML - ASML Holding' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom' },
                { name: 'NASDAQ:COIN', displayName: 'COIN - Coinbase Global' },
                { name: 'NYSE:CRCL', displayName: 'CRCL - Circle Internet Group' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet' },
                { name: 'NASDAQ:HOOD', displayName: 'HOOD - Robinhood Markets' },
                { name: 'NASDAQ:INTC', displayName: 'INTC - Intel' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft' },
                { name: 'NASDAQ:MSTR', displayName: 'MSTR - MicroStrategy' },
                { name: 'NASDAQ:MU', displayName: 'MU - Micron Technology' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix' },
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA' },
                { name: 'NYSE:ORCL', displayName: 'ORCL - Oracle' },
                { name: 'NASDAQ:PLTR', displayName: 'PLTR - Palantir Technologies' },
                { name: 'NASDAQ:QQQ', displayName: 'QQQ - Invesco QQQ Trust' },
                { name: 'AMEX:SPY', displayName: 'SPY - SPDR S&P 500 ETF' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla' },
                { name: 'NYSE:TSM', displayName: 'TSM - Taiwan Semiconductor' },
            ],
        },
        {
            name: 'GDLC',
            sourceUrl: 'https://etfs.grayscale.com/gdlc',
            symbols: [
                { name: 'BINANCE:BTCUSDT', displayName: 'BTC - Bitcoin (73.52%)' },
                { name: 'BINANCE:ETHUSDT', displayName: 'ETH - Ethereum (16.16%)' },
                { name: 'BINANCE:XRPUSDT', displayName: 'XRP - Ripple (5.05%)' },
                { name: 'BINANCE:SOLUSDT', displayName: 'SOL - Solana (3.83%)' },
                { name: 'BINANCE:ADAUSDT', displayName: 'ADA - Cardano (1.44%)' },
            ],
        },

    ],
};

export const CRYPTO_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'crypto',
    width: '100%',
    height: '600',
};

export const CRYPTO_TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'BINANCE:BTCUSDT',
            title: 'Bitcoin'
        },
        {
            proName: 'BINANCE:ETHUSDT',
            title: 'Ethereum'
        },
        {
            proName: 'NASDAQ:COIN',
            title: 'Coinbase'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
