// Crypto Page Configuration

export const CRYPTO_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'ETF',
            symbols: [
                { s: 'OTC:BITW', d: 'Bitwise 10 Crypto Index Fund' },
                { s: 'AMEX:GDLC', d: 'Grayscale Digital Large Cap Fund' },
                { s: 'AMEX:CRPT', d: 'First Trust SkyBridge Crypto ETF' },
                { s: 'NASDAQ:COIN', d: 'Coinbase Global Inc' },
                { s: 'NASDAQ:HOOD', d: 'Robinhood Markets Inc' },
            ],
        },
        {
            title: 'BTC',
            symbols: [
                { s: 'NASDAQ:IBIT', d: 'iShares Bitcoin Trust ETF' },
                { s: 'AMEX:FBTC', d: 'Fidelity Bitcoin Fund' },
                { s: 'AMEX:BITB', d: 'Bitwise Bitcoin ETF' },
                { s: 'AMEX:ARKB', d: 'ARK 21Shares Bitcoin ETF' },
                { s: 'AMEX:HODL', d: 'VanEck Bitcoin Trust' },
                { s: 'NASDAQ:MSTR', d: 'MicroStrategy Incorporated' },
                { s: 'NASDAQ:MARA', d: 'Marathon Digital Holdings' },
                { s: 'NASDAQ:RIOT', d: 'Riot Platforms Inc' },
            ],
        },
        {
            title: 'ETH',
            symbols: [
                { s: 'NASDAQ:ETHA', d: 'iShares Ethereum Trust ETF' },
                { s: 'AMEX:FETH', d: 'Fidelity Ethereum Fund' },
                { s: 'AMEX:ETHW', d: 'Bitwise Ethereum ETF' },
            ],
        },
        {
            title: 'Exchanges',
            symbols: [
                { s: 'NASDAQ:COIN', d: 'Coinbase Global Inc' },
                { s: 'NASDAQ:HOOD', d: 'Robinhood Markets Inc' },
                { s: 'NASDAQ:PYPL', d: 'PayPal Holdings Inc' },
                { s: 'NASDAQ:CME', d: 'CME Group Inc' },
                { s: 'NASDAQ:SOFI', d: 'SoFi Technologies Inc' },
            ],
        },
        {
            title: 'Blockchain',
            symbols: [
                { s: 'NASDAQ:BKCH', d: 'Global X Blockchain ETF' },
                { s: 'AMEX:BLOK', d: 'Amplify Transformational Data ETF' },
                { s: 'AMEX:BITQ', d: 'Bitwise Crypto Innovators ETF' },
                { s: 'AMEX:BLKC', d: 'Invesco Galaxy Blockchain ETF' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const CRYPTO_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'Crypto',
    blockSize: 'market_cap_calc',
    blockColor: 'change',
    grouping: 'no_group',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const CRYPTO_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Crypto Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'BITW',
            sourceUrl: 'https://bitwiseinvestments.com/crypto-funds/bitw',
            symbols: [
                { name: 'BINANCE:BTCUSDT', displayName: 'BTC - Bitcoin (72.9%)' },
                { name: 'BINANCE:ETHUSDT', displayName: 'ETH - Ethereum (16.3%)' },
                { name: 'BINANCE:XRPUSDT', displayName: 'XRP - Ripple (4.9%)' },
                { name: 'BINANCE:SOLUSDT', displayName: 'SOL - Solana (3.5%)' },
                { name: 'BINANCE:ADAUSDT', displayName: 'ADA - Cardano (0.8%)' },
                { name: 'BINANCE:LINKUSDT', displayName: 'LINK - Chainlink (0.4%)' },
                { name: 'BINANCE:SUIUSDT', displayName: 'SUI - Sui (0.3%)' },
                { name: 'BINANCE:AVAXUSDT', displayName: 'AVAX - Avalanche (0.3%)' },
                { name: 'BINANCE:LTCUSDT', displayName: 'LTC - Litecoin (0.2%)' },
                { name: 'BINANCE:DOTUSDT', displayName: 'DOT - Polkadot (0.2%)' },
            ],
        },
        {
            name: 'CRPT',
            sourceUrl: 'https://www.ftportfolios.com/Retail/Etf/EtfHoldings.aspx?Ticker=CRPT',
            symbols: [
                { name: 'NASDAQ:MSTR', displayName: 'MSTR - MicroStrategy (17.80%)' },
                { name: 'NASDAQ:COIN', displayName: 'COIN - Coinbase Global (16.99%)' },
                { name: 'NASDAQ:GLXY', displayName: 'GLXY - Galaxy Digital (11.72%)' },
                { name: 'NASDAQ:HOOD', displayName: 'HOOD - Robinhood Markets (7.46%)' },
                { name: 'NASDAQ:CIFR', displayName: 'CIFR - Cipher Mining (2.15%)' },
                { name: 'NASDAQ:WULF', displayName: 'WULF - TeraWulf (1.99%)' },
                { name: 'NASDAQ:IREN', displayName: 'IREN - IREN Ltd (1.94%)' },
                { name: 'NASDAQ:FORD', displayName: 'FORD - Forward Industries (1.63%)' },
                { name: 'NASDAQ:CLSK', displayName: 'CLSK - CleanSpark (1.10%)' },
                { name: 'NASDAQ:HIVE', displayName: 'HIVE - HIVE Digital Technologies (0.83%)' },
                { name: 'NASDAQ:RIOT', displayName: 'RIOT - Riot Platforms (0.78%)' },
                { name: 'NASDAQ:MARA', displayName: 'MARA - MARA Holdings (0.52%)' },
                { name: 'NASDAQ:BTDR', displayName: 'BTDR - Bitdeer Technologies (0.45%)' },
                { name: 'NASDAQ:DJT', displayName: 'DJT - Trump Media & Technology (0.24%)' },
            ],
        },
        {
            name: 'GDLC',
            sourceUrl: 'https://etfs.grayscale.com/gdlc',
            symbols: [
                { name: 'BINANCE:BTCUSDT', displayName: 'BTC - Bitcoin (73.52%)' },
                { name: 'BINANCE:ETHUSDT', displayName: 'ETH - Ethereum (16.16%)' },
                { name: 'BINANCE:XRPUSDT', displayName: 'XRP - Ripple (5.05%)' },
                { name: 'BINANCE:SOLUSDT', displayName: 'SOL - Solana (3.83%)' },
                { name: 'BINANCE:ADAUSDT', displayName: 'ADA - Cardano (1.44%)' },
            ],
        },
    ],
};

export const CRYPTO_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'crypto',
    width: '100%',
    height: '600',
};
