// Dow Jones 30 Page Configuration

export const DOW30_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'ETF',
            symbols: [
                { s: 'AMEX:DIA', d: 'SPDR Dow Jones Industrial Average ETF' },
                { s: 'AMEX:DJD', d: 'Invesco Dow Jones Industrial Average Dividend ETF' },
                { s: 'AMEX:EDOW', d: 'First Trust Dow 30 Equal Weight ETF' },
                { s: 'AMEX:DJIA', d: 'Global X Dow 30 Covered Call ETF' },
                { s: 'AMEX:DDM', d: 'ProShares Ultra Dow30' },
                { s: 'AMEX:DXD', d: 'ProShares UltraShort Dow30' },
            ],
        },
        {
            title: 'Technology',
            symbols: [
                { s: 'NASDAQ:NVDA', d: 'NVIDIA Corporation' },
                { s: 'NASDAQ:AAPL', d: 'Apple Inc' },
                { s: 'NASDAQ:CSCO', d: 'Cisco Systems Inc' },
                { s: 'NYSE:BA', d: 'Boeing Company' },
                { s: 'NASDAQ:HON', d: 'Honeywell International Inc' },
            ],
        },
        {
            title: 'Services',
            symbols: [
                { s: 'NASDAQ:MSFT', d: 'Microsoft Corporation' },
                { s: 'NYSE:IBM', d: 'International Business Machines' },
                { s: 'NYSE:CRM', d: 'Salesforce Inc' },
                { s: 'NYSE:MCD', d: 'McDonald\'s Corporation' },
                { s: 'NYSE:DIS', d: 'Walt Disney Company' },
                { s: 'NYSE:NKE', d: 'Nike Inc' },
            ],
        },
        {
            title: 'Finance',
            symbols: [
                { s: 'NYSE:JPM', d: 'JPMorgan Chase & Co' },
                { s: 'NYSE:V', d: 'Visa Inc' },
                { s: 'NYSE:GS', d: 'Goldman Sachs Group Inc' },
                { s: 'NYSE:AXP', d: 'American Express Company' },
                { s: 'NYSE:TRV', d: 'Travelers Companies Inc' },
            ],
        },
        {
            title: 'Retail',
            symbols: [
                { s: 'NASDAQ:AMZN', d: 'AMZN - Amazon.com, Inc.' },
                { s: 'NYSE:WMT', d: 'Walmart Inc' },
                { s: 'NYSE:HD', d: 'Home Depot Inc' },
                { s: 'NYSE:PG', d: 'Procter & Gamble Company' },
                { s: 'NYSE:KO', d: 'Coca-Cola Company' },
            ],
        },


    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const DOW30_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'DJDJI',
    blockSize: 'market_cap_basic',
    blockColor: 'change',
    grouping: 'sector',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const DOW30_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Dow Jones 30 Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'DIA',
            sourceUrl: 'https://stockanalysis.com/etf/dia/holdings/',
            symbols: [
                { name: 'NYSE:GS', displayName: 'GS - The Goldman Sachs Group, Inc. (10.24%)' },
                { name: 'NYSE:CAT', displayName: 'CAT - Caterpillar Inc. (7.00%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (6.82%)' },
                { name: 'NYSE:HD', displayName: 'HD - The Home Depot, Inc. (5.15%)' },
                { name: 'NYSE:UNH', displayName: 'UNH - UnitedHealth Group Incorporated (4.78%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (4.63%)' },
                { name: 'NYSE:SHW', displayName: 'SHW - The Sherwin-Williams Company (4.45%)' },
                { name: 'NYSE:AXP', displayName: 'AXP - American Express Company (4.42%)' },
                { name: 'NYSE:MCD', displayName: 'MCD - McDonald\'s Corporation (4.04%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (4.01%)' },
                { name: 'NASDAQ:AMGN', displayName: 'AMGN - Amgen Inc. (3.90%)' },
                { name: 'NYSE:IBM', displayName: 'IBM - International Business Machines Corporation (3.67%)' },
                { name: 'NYSE:TRV', displayName: 'TRV - The Travelers Companies, Inc. (3.66%)' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (3.29%)' },
                { name: 'NYSE:CRM', displayName: 'CRM - Salesforce, Inc. (3.18%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (2.87%)' },
                { name: 'NYSE:BA', displayName: 'BA - The Boeing Company (2.85%)' },
                { name: 'NASDAQ:HON', displayName: 'HON - Honeywell International Inc. (2.77%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (2.53%)' },
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation (2.39%)' },
                { name: 'NYSE:MMM', displayName: 'MMM - 3M Company (2.03%)' },
                { name: 'NYSE:CVX', displayName: 'CVX - Chevron Corporation (2.02%)' },
                { name: 'NYSE:PG', displayName: 'PG - The Procter & Gamble Company (1.98%)' },
                { name: 'NYSE:DIS', displayName: 'DIS - The Walt Disney Company (1.48%)' },
                { name: 'NYSE:WMT', displayName: 'WMT - Walmart Inc. (1.42%)' },
            ],
        },
        {
            name: 'DJD',
            sourceUrl: 'https://stockanalysis.com/etf/djd/holdings/',
            symbols: [
                { name: 'NYSE:VZ', displayName: 'VZ - Verizon Communications Inc. (10.13%)' },
                { name: 'NYSE:MRK', displayName: 'MRK - Merck & Co., Inc. (7.11%)' },
                { name: 'NYSE:CVX', displayName: 'CVX - Chevron Corporation (7.07%)' },
                { name: 'NASDAQ:AMGN', displayName: 'AMGN - Amgen Inc. (6.28%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (5.50%)' },
                { name: 'NYSE:IBM', displayName: 'IBM - International Business Machines Corporation (5.36%)' },
                { name: 'NYSE:UNH', displayName: 'UNH - UnitedHealth Group Incorporated (5.07%)' },
                { name: 'NYSE:KO', displayName: 'KO - The Coca-Cola Company (5.01%)' },
                { name: 'NYSE:PG', displayName: 'PG - The Procter & Gamble Company (4.35%)' },
                { name: 'NASDAQ:CSCO', displayName: 'CSCO - Cisco Systems, Inc. (4.15%)' },
                { name: 'NYSE:MCD', displayName: 'MCD - McDonald\'s Corporation (4.01%)' },
                { name: 'NYSE:HD', displayName: 'HD - The Home Depot, Inc. (3.67%)' },
                { name: 'NASDAQ:HON', displayName: 'HON - Honeywell International Inc. (3.57%)' },
                { name: 'NYSE:NKE', displayName: 'NKE - NIKE, Inc. (3.40%)' },
                { name: 'NYSE:MMM', displayName: 'MMM - 3M Company (3.20%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (3.08%)' },
                { name: 'NYSE:GS', displayName: 'GS - The Goldman Sachs Group, Inc. (2.98%)' },
                { name: 'NYSE:CAT', displayName: 'CAT - Caterpillar Inc. (2.91%)' },
                { name: 'NYSE:TRV', displayName: 'TRV - The Travelers Companies, Inc. (2.78%)' },
                { name: 'NYSE:WMT', displayName: 'WMT - Walmart Inc. (1.57%)' },
                { name: 'NYSE:AXP', displayName: 'AXP - American Express Company (1.53%)' },
                { name: 'NYSE:DIS', displayName: 'DIS - The Walt Disney Company (1.46%)' },
                { name: 'NYSE:SHW', displayName: 'SHW - The Sherwin-Williams Company (1.31%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (1.23%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (1.22%)' },
            ],
        },
    ],
};

export const DOW30_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'stock',
    width: '100%',
    height: '600',
};

export const DOW30_TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'BLACKBULL:US30',
            title: 'Dow Jones 30'
        },
        {
            proName: 'AMEX:DIA',
            title: 'DIA'
        },
        {
            proName: 'FOREXCOM:DJI',
            title: 'Dow Jones Index CFD'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
