// ETF Page Configuration

export const ETF_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'Commodity',
            symbols: [
                { s: 'AMEX:GLD', d: 'SPDR Gold Trust' },
                { s: 'AMEX:SLV', d: 'iShares Silver Trust' },
                { s: 'AMEX:USO', d: 'United States Oil Fund' },
                { s: 'AMEX:UNG', d: 'United States Natural Gas Fund' },
                { s: 'AMEX:DBA', d: 'Invesco DB Agriculture Fund' },
                { s: 'AMEX:DBB', d: 'Invesco DB Base Metals Fund' },
                { s: 'AMEX:DBC', d: 'Invesco DB Commodity Index Tracking Fund' },
                { s: 'AMEX:DBE', d: 'Invesco DB Energy Fund' },
            ],
        },
        {
            title: 'International',
            symbols: [
                { s: 'NASDAQ:VXUS', d: 'Vanguard Total International Stock ETF' },
                { s: 'AMEX:EFA', d: 'iShares MSCI EAFE ETF' },
                { s: 'AMEX:IEFA', d: 'iShares Core MSCI EAFE ETF' },
                { s: 'AMEX:VEA', d: 'Vanguard FTSE Developed Markets ETF' },
                { s: 'AMEX:VWO', d: 'Vanguard FTSE Emerging Markets ETF' },
                { s: 'AMEX:IEMG', d: 'iShares Core MSCI Emerging Markets ETF' },
                { s: 'AMEX:EEM', d: 'iShares MSCI Emerging Markets ETF' },
                { s: 'NASDAQ:ACWI', d: 'iShares MSCI ACWI ETF' },
            ],
        },
        {
            title: 'SPDR',
            symbols: [
                { s: 'AMEX:XLK', d: 'Technology Select Sector SPDR Fund' },
                { s: 'AMEX:XLF', d: 'Financial Select Sector SPDR Fund' },
                { s: 'AMEX:XLE', d: 'Energy Select Sector SPDR Fund' },
                { s: 'AMEX:XLV', d: 'Health Care Select Sector SPDR Fund' },
                { s: 'AMEX:XLI', d: 'Industrial Select Sector SPDR Fund' },
                { s: 'AMEX:XLP', d: 'Consumer Staples Select Sector SPDR Fund' },
                { s: 'AMEX:XLY', d: 'Consumer Discretionary Select Sector SPDR Fund' },
                { s: 'AMEX:XLB', d: 'Materials Select Sector SPDR Fund' },
                { s: 'AMEX:XLRE', d: 'Real Estate Select Sector SPDR Fund' },
                { s: 'AMEX:XLU', d: 'Utilities Select Sector SPDR Fund' },
                { s: 'AMEX:XLC', d: 'Communication Services Select Sector SPDR Fund' }
            ],
        },
        {
            title: 'Vanguard',
            symbols: [
                { s: 'AMEX:VGT', d: 'Vanguard Information Technology ETF' },
                { s: 'AMEX:VFH', d: 'Vanguard Financials ETF' },
                { s: 'AMEX:VDE', d: 'Vanguard Energy ETF' },
                { s: 'AMEX:VHT', d: 'Vanguard Health Care ETF' },
                { s: 'AMEX:VIS', d: 'Vanguard Industrials ETF' },
                { s: 'AMEX:VDC', d: 'Vanguard Consumer Staples ETF' },
                { s: 'AMEX:VCR', d: 'Vanguard Consumer Discretionary ETF' },
                { s: 'AMEX:VAW', d: 'Vanguard Materials ETF' },
                { s: 'AMEX:VNQ', d: 'Vanguard Real Estate ETF' },
                { s: 'AMEX:VPU', d: 'Vanguard Utilities ETF' },
                { s: 'AMEX:VOX', d: 'Vanguard Communication Services ETF' }
            ],
        },
        {
            title: 'iShares',
            symbols: [
                { s: 'AMEX:IYW', d: 'iShares U.S. Technology ETF' },
                { s: 'AMEX:IYF', d: 'iShares U.S. Financials ETF' },
                { s: 'AMEX:IYE', d: 'iShares U.S. Energy ETF' },
                { s: 'AMEX:IYH', d: 'iShares U.S. Healthcare ETF' },
                { s: 'AMEX:IYJ', d: 'iShares U.S. Industrials ETF' },
                { s: 'AMEX:IYK', d: 'iShares U.S. Consumer Staples ETF' },
                { s: 'AMEX:IYC', d: 'iShares U.S. Consumer Discretionary ETF' },
                { s: 'AMEX:IYM', d: 'iShares U.S. Basic Materials ETF' },
                { s: 'AMEX:IYR', d: 'iShares U.S. Real Estate ETF' },
                { s: 'AMEX:IDU', d: 'iShares U.S. Utilities ETF' },
                { s: 'AMEX:IYZ', d: 'iShares U.S. Telecommunications ETF' }
            ],
        },
        {
            title: 'Invesco',
            symbols: [
                { s: 'NASDAQ:PTF', d: 'Invesco DWA Technology Momentum ETF' },
                { s: 'NASDAQ:PFI', d: 'Invesco DWA Financial Momentum ETF' },
                { s: 'AMEX:PXE', d: 'Invesco DWA Energy Momentum ETF' },
                { s: 'NASDAQ:PTH', d: 'Invesco DWA Healthcare Momentum ETF' },
                { s: 'NASDAQ:PRN', d: 'Invesco DWA Industrials Momentum ETF' },
                { s: 'NASDAQ:PSL', d: 'Invesco DWA Consumer Staples Momentum ETF' },
                { s: 'NASDAQ:PEZ', d: 'Invesco DWA Consumer Cyclicals Momentum ETF' },
                { s: 'NASDAQ:PYZ', d: 'Invesco DWA Basic Materials Momentum ETF' },
                { s: 'AMEX:PSR', d: 'Invesco Active U.S. Real Estate ETF' },
                { s: 'NASDAQ:PUI', d: 'Invesco DWA Utilities Momentum ETF' },
                { s: 'NASDAQ:PXI', d: 'Invesco DWA Communication Services Momentum ETF' }
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const ETF_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'AllUSEtf',
    blockSize: 'Value.Traded',
    blockColor: 'change',
    grouping: 'asset_class',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const ETF_MARKET_DATA_WIDGET_CONFIG = {
    title: 'ETFs',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'Global',
            sourceUrl: 'https://stockanalysis.com/etf/',
            symbols: [
                { name: 'NASDAQ:ACWI', displayName: 'ACWI - iShares MSCI ACWI' },
                { name: 'AMEX:VT', displayName: 'VT - Vanguard Total World Stock' },
                { name: 'AMEX:URTH', displayName: 'URTH - iShares MSCI World' },
                { name: 'AMEX:IOO', displayName: 'IOO - iShares Global 100' },
                { name: 'NASDAQ:VXUS', displayName: 'VXUS - Vanguard Total International Stock' },
                { name: 'AMEX:EFA', displayName: 'EFA - iShares MSCI EAFE' },
                { name: 'AMEX:IEFA', displayName: 'IEFA - iShares Core MSCI EAFE' },
                { name: 'AMEX:VEA', displayName: 'VEA - Vanguard FTSE Developed Markets' },
                { name: 'AMEX:VWO', displayName: 'VWO - Vanguard FTSE Emerging Markets' },
                { name: 'AMEX:IEMG', displayName: 'IEMG - iShares Core MSCI Emerging Markets' },
                { name: 'AMEX:EEM', displayName: 'EEM - iShares MSCI Emerging Markets' },
                { name: 'AMEX:VEU', displayName: 'VEU - Vanguard FTSE All-World ex-US' },
                { name: 'NASDAQ:IXUS', displayName: 'IXUS - iShares Core MSCI Total International Stock' },
                { name: 'AMEX:SPDW', displayName: 'SPDW - SPDR Portfolio Developed World ex-US' },
                { name: 'AMEX:SPEM', displayName: 'SPEM - SPDR Portfolio Emerging Markets' },
                { name: 'AMEX:VSS', displayName: 'VSS - Vanguard FTSE All-World ex-US Small-Cap' },
                { name: 'NASDAQ:SCZ', displayName: 'SCZ - iShares MSCI EAFE Small-Cap' },
                { name: 'AMEX:FNDF', displayName: 'FNDF - Schwab Fundamental International Large Company' },
                { name: 'AMEX:AVEM', displayName: 'AVEM - Avantis Emerging Markets Equity' },
                { name: 'AMEX:DFAE', displayName: 'DFAE - Dimensional Emerging Markets Core Equity' },
            ],
        },
        {
            name: 'Country',
            sourceUrl: 'https://etfdb.com/tool/etf-country-exposure-tool/',
            symbols: [
                { name: 'AMEX:VTI', displayName: 'VTI - USA (Total Market)' },
                { name: 'AMEX:VUG', displayName: 'VUG - USA (Growth)' },
                { name: 'AMEX:VTV', displayName: 'VTV - USA (Value)' },
                { name: 'AMEX:CNYA', displayName: 'CNYA - China' },
                { name: 'AMEX:EWG', displayName: 'EWG - Germany' },
                { name: 'AMEX:EWJ', displayName: 'EWJ - Japan' },
                { name: 'AMEX:INDA', displayName: 'INDA - India' },
                { name: 'AMEX:EWU', displayName: 'EWU - United Kingdom' },
                { name: 'AMEX:EWQ', displayName: 'EWQ - France' },
                { name: 'AMEX:EWI', displayName: 'EWI - Italy' },
                { name: 'AMEX:EWC', displayName: 'EWC - Canada' },
                { name: 'AMEX:EWZ', displayName: 'EWZ - Brazil' },
                { name: 'AMEX:EWW', displayName: 'EWW - Mexico' },
                { name: 'AMEX:EWA', displayName: 'EWA - Australia' },
                { name: 'AMEX:EWP', displayName: 'EWP - Spain' },
                { name: 'AMEX:EWY', displayName: 'EWY - South Korea' },
                { name: 'AMEX:EIDO', displayName: 'EIDO - Indonesia' },
                { name: 'NASDAQ:TUR', displayName: 'TUR - Turkey' },
                { name: 'AMEX:KSA', displayName: 'KSA - Saudi Arabia' },
                { name: 'AMEX:EWN', displayName: 'EWN - Netherlands' },
                { name: 'AMEX:EWL', displayName: 'EWL - Switzerland' },
                { name: 'AMEX:EPOL', displayName: 'EPOL - Poland' },
                { name: 'AMEX:EWT', displayName: 'EWT - Taiwan' },
                { name: 'AMEX:EWK', displayName: 'EWK - Belgium' },
                { name: 'AMEX:ARGT', displayName: 'ARGT - Argentina' },
                { name: 'AMEX:EWD', displayName: 'EWD - Sweden' },
                { name: 'AMEX:EIRL', displayName: 'EIRL - Ireland' },
                { name: 'AMEX:EWS', displayName: 'EWS - Singapore' },
                { name: 'AMEX:EIS', displayName: 'EIS - Israel' },
                { name: 'NASDAQ:UAE', displayName: 'UAE - United Arab Emirates' },
                { name: 'AMEX:THD', displayName: 'THD - Thailand' },
                { name: 'AMEX:EWO', displayName: 'EWO - Austria' },
                { name: 'AMEX:NORW', displayName: 'NORW - Norway' },
                { name: 'AMEX:EPHE', displayName: 'EPHE - Philippines' },
            ],
        },
    ],
};

export const ETF_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'index',
    width: '100%',
    height: '600',
};

export const ETF_TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'AMEX:VT',
            title: 'VT'
        },
        {
            proName: 'AMEX:VTI',
            title: 'VTI'
        },
        {
            proName: 'AMEX:VEU',
            title: 'VEU'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
