// ETF Page Configuration

export const ETF_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'Index',
            symbols: [
                { s: 'AMEX:SPY', d: 'SPDR S&P 500 ETF' },
                { s: 'NASDAQ:QQQ', d: 'Invesco QQQ Trust' },
                { s: 'AMEX:DIA', d: 'SPDR Dow Jones Industrial Average ETF' },
                { s: 'AMEX:IWM', d: 'iShares Russell 2000 ETF' },
                { s: 'AMEX:VTI', d: 'Vanguard Total Stock Market ETF' },
                { s: 'AMEX:VOO', d: 'Vanguard S&P 500 ETF' },
                { s: 'AMEX:IVV', d: 'iShares Core S&P 500 ETF' },
                { s: 'AMEX:MDY', d: 'SPDR S&P MidCap 400 ETF' },
            ],
        },
        {
            title: 'International',
            symbols: [
                { s: 'NASDAQ:VXUS', d: 'Vanguard Total International Stock ETF' },
                { s: 'AMEX:EFA', d: 'iShares MSCI EAFE ETF' },
                { s: 'AMEX:IEFA', d: 'iShares Core MSCI EAFE ETF' },
                { s: 'AMEX:VEA', d: 'Vanguard FTSE Developed Markets ETF' },
                { s: 'AMEX:VWO', d: 'Vanguard FTSE Emerging Markets ETF' },
                { s: 'AMEX:IEMG', d: 'iShares Core MSCI Emerging Markets ETF' },
                { s: 'AMEX:EEM', d: 'iShares MSCI Emerging Markets ETF' },
                { s: 'NASDAQ:ACWI', d: 'iShares MSCI ACWI ETF' },
            ],
        },
        {
            title: 'SPDR',
            symbols: [
                { s: 'AMEX:XLK', d: 'Technology Select Sector SPDR Fund' },
                { s: 'AMEX:XLF', d: 'Financial Select Sector SPDR Fund' },
                { s: 'AMEX:XLE', d: 'Energy Select Sector SPDR Fund' },
                { s: 'AMEX:XLV', d: 'Health Care Select Sector SPDR Fund' },
                { s: 'AMEX:XLI', d: 'Industrial Select Sector SPDR Fund' },
                { s: 'AMEX:XLP', d: 'Consumer Staples Select Sector SPDR Fund' },
                { s: 'AMEX:XLY', d: 'Consumer Discretionary Select Sector SPDR Fund' },
                { s: 'AMEX:XLB', d: 'Materials Select Sector SPDR Fund' },
                { s: 'AMEX:XLRE', d: 'Real Estate Select Sector SPDR Fund' },
                { s: 'AMEX:XLU', d: 'Utilities Select Sector SPDR Fund' },
                { s: 'AMEX:XLC', d: 'Communication Services Select Sector SPDR Fund' }
            ],
        },
        {
            title: 'Vanguard',
            symbols: [
                { s: 'AMEX:VGT', d: 'Vanguard Information Technology ETF' },
                { s: 'AMEX:VFH', d: 'Vanguard Financials ETF' },
                { s: 'AMEX:VDE', d: 'Vanguard Energy ETF' },
                { s: 'AMEX:VHT', d: 'Vanguard Health Care ETF' },
                { s: 'AMEX:VIS', d: 'Vanguard Industrials ETF' },
                { s: 'AMEX:VDC', d: 'Vanguard Consumer Staples ETF' },
                { s: 'AMEX:VCR', d: 'Vanguard Consumer Discretionary ETF' },
                { s: 'AMEX:VAW', d: 'Vanguard Materials ETF' },
                { s: 'AMEX:VNQ', d: 'Vanguard Real Estate ETF' },
                { s: 'AMEX:VPU', d: 'Vanguard Utilities ETF' },
                { s: 'AMEX:VOX', d: 'Vanguard Communication Services ETF' }
            ],
        },
        {
            title: 'iShares',
            symbols: [
                { s: 'AMEX:IYW', d: 'iShares U.S. Technology ETF' },
                { s: 'AMEX:IYF', d: 'iShares U.S. Financials ETF' },
                { s: 'AMEX:IYE', d: 'iShares U.S. Energy ETF' },
                { s: 'AMEX:IYH', d: 'iShares U.S. Healthcare ETF' },
                { s: 'AMEX:IYJ', d: 'iShares U.S. Industrials ETF' },
                { s: 'AMEX:IYK', d: 'iShares U.S. Consumer Staples ETF' },
                { s: 'AMEX:IYC', d: 'iShares U.S. Consumer Discretionary ETF' },
                { s: 'AMEX:IYM', d: 'iShares U.S. Basic Materials ETF' },
                { s: 'AMEX:IYR', d: 'iShares U.S. Real Estate ETF' },
                { s: 'AMEX:IDU', d: 'iShares U.S. Utilities ETF' },
                { s: 'AMEX:IYZ', d: 'iShares U.S. Telecommunications ETF' }
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const ETF_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'AllUSEtf',
    blockSize: 'aum',
    blockColor: 'change',
    grouping: 'asset_class',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const ETF_MARKET_DATA_WIDGET_CONFIG = {
    title: 'ETFs',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'SPY',
            sourceUrl: 'https://stockanalysis.com/etf/spy/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc.' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc.' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc.' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc.' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc.' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc.' },
                { name: 'NYSE:BRK.B', displayName: 'BRK.B - Berkshire Hathaway Inc.' },
            ],
        },
        {
            name: 'QQQ',
            sourceUrl: 'https://stockanalysis.com/etf/qqq/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc.' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc.' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc.' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc.' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc.' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc.' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc.' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc.' },
            ],
        },
        {
            name: 'DIA',
            sourceUrl: 'https://stockanalysis.com/etf/dia/holdings/',
            symbols: [
                { name: 'NYSE:GS', displayName: 'GS - The Goldman Sachs Group, Inc.' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation' },
                { name: 'NYSE:CAT', displayName: 'CAT - Caterpillar Inc.' },
                { name: 'NYSE:HD', displayName: 'HD - The Home Depot, Inc.' },
                { name: 'NYSE:UNH', displayName: 'UNH - UnitedHealth Group Incorporated' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc.' },
                { name: 'NYSE:SHW', displayName: 'SHW - The Sherwin-Williams Company' },
                { name: 'NYSE:AXP', displayName: 'AXP - American Express Company' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co.' },
                { name: 'NASDAQ:AMGN', displayName: 'AMGN - Amgen Inc.' },
            ],
        },
    ],
};

export const ETF_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'index',
    width: '100%',
    height: '600',
};
