// Nasdaq 100 Page Configuration

export const NASDAQ100_MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'Taiwan Related',
            symbols: [
                { s: 'NASDAQ:QQQ', d: 'Invesco QQQ Trust' },
                { s: 'AMEX:UUP', d: 'Invesco DB US Dollar Index Bullish Fund' },
                { s: 'AMEX:EWT', d: 'iShares MSCI Taiwan ETF' },
                { s: 'NYSE:TSM', d: 'Taiwan Semiconductor Manufacturing' }, // 台積電
                { s: 'NYSE:UMC', d: 'United Microelectronics Corp' }, // 聯電
                { s: 'NYSE:CHT', d: 'Chunghwa Telecom' }, // 中華電信
                { s: 'NYSE:ASX', d: 'ASE Technology Holding' }, //  日月光
                { s: 'NYSE:HMC', d: 'Hon Hai Precision (Foxconn)' }, // 鴻海 (Foxconn)
                { s: 'NASDAQ:HTHT', d: 'Himax Technologies' }, // 奇景光電
            ],
        },
        {
            title: 'Technology',
            symbols: [
                { s: 'NASDAQ:NVDA', d: 'NVIDIA Corporation' },
                { s: 'NASDAQ:MSFT', d: 'Microsoft Corporation' },
                { s: 'NASDAQ:AAPL', d: 'Apple Inc' },
                { s: 'NASDAQ:AVGO', d: 'Broadcom Inc' },
                { s: 'NASDAQ:GOOGL', d: 'Alphabet Inc' },
                { s: 'NASDAQ:TSLA', d: 'Tesla Inc' },
                { s: 'NASDAQ:GOOG', d: 'Alphabet Inc' },
                { s: 'NYSE:ORCL', d: 'Oracle Corporation' },
                { s: 'NASDAQ:AMD', d: 'Advanced Micro Devices' },
            ],
        },
        {
            title: 'Services',
            symbols: [
                { s: 'NASDAQ:META', d: 'Meta Platforms Inc' },
                { s: 'NASDAQ:NFLX', d: 'Netflix Inc' },
                { s: 'NASDAQ:PLTR', d: 'Palantir Technologies Inc' },
                { s: 'NASDAQ:PEP', d: 'PepsiCo Inc' },
                { s: 'NASDAQ:TMUS', d: 'T-Mobile US Inc' },
                { s: 'NASDAQ:LIN', d: 'Linde plc' },
                { s: 'NASDAQ:MU', d: 'Micron Technology Inc' },
            ],
        },
        {
            title: 'Retail',
            symbols: [
                { s: 'NASDAQ:AMZN', d: 'Amazon.com Inc' },
                { s: 'NASDAQ:COST', d: 'Costco Wholesale Corp' },
                { s: 'NASDAQ:PDD', d: 'PDD Holdings Inc' },
                { s: 'NASDAQ:MELI', d: 'MercadoLibre Inc' },
                { s: 'NASDAQ:ORLY', d: "O'Reilly Automotive Inc" },
                { s: 'NASDAQ:ROST', d: 'Ross Stores Inc' },
                { s: 'NASDAQ:CPRT', d: 'Copart Inc' },
            ],
        },
        {
            title: 'Consumer',
            symbols: [
                { s: 'NASDAQ:BKNG', d: 'Booking Holdings Inc' },
                { s: 'NASDAQ:SBUX', d: 'Starbucks Corporation' },
                { s: 'NASDAQ:CTAS', d: 'Cintas Corporation' },
                { s: 'NASDAQ:CMCSA', d: 'Comcast Corporation' },
                { s: 'NASDAQ:ABNB', d: 'Airbnb Inc' },
                { s: 'NASDAQ:MAR', d: 'Marriott International Inc' },
                { s: 'NASDAQ:WBD', d: 'Warner Bros. Discovery Inc' },
                { s: 'NASDAQ:CHTR', d: 'Charter Communications Inc' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const NASDAQ100_HEATMAP_WIDGET_CONFIG = {
    dataSource: 'NASDAQ100',
    blockSize: 'market_cap_basic',
    blockColor: 'change',
    grouping: 'sector',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const NASDAQ100_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Nasdaq 100 Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'QQQ',
            sourceUrl: 'https://stockanalysis.com/etf/qqq/holdings/',
            symbols: [
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc.' },
                { name: 'NASDAQ:ABNB', displayName: 'ABNB - Airbnb, Inc.' },
                { name: 'NASDAQ:ADBE', displayName: 'ADBE - Adobe Inc.' },
                { name: 'NASDAQ:ADI', displayName: 'ADI - Analog Devices, Inc.' },
                { name: 'NASDAQ:ADP', displayName: 'ADP - Automatic Data Processing, Inc.' },
                { name: 'NASDAQ:ADSK', displayName: 'ADSK - Autodesk, Inc.' },
                { name: 'NASDAQ:AEP', displayName: 'AEP - American Electric Power Company, Inc.' },
                { name: 'NASDAQ:ALAB', displayName: 'ALAB - Astera Labs, Inc.' },
                { name: 'NASDAQ:ALNY', displayName: 'ALNY - Alnylam Pharmaceuticals, Inc.' },
                { name: 'NASDAQ:AMAT', displayName: 'AMAT - Applied Materials, Inc.' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices, Inc.' },
                { name: 'NASDAQ:AMGN', displayName: 'AMGN - Amgen Inc.' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc.' },
                { name: 'NASDAQ:APP', displayName: 'APP - Applovin Corporation' },
                { name: 'NASDAQ:ARM', displayName: 'ARM - Arm Holdings plc' },
                { name: 'NASDAQ:ASML', displayName: 'ASML - ASML Holding N.V. New York Registry Shares' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc.' },
                { name: 'NASDAQ:AXON', displayName: 'AXON - Axon Enterprise, Inc.' },
                { name: 'NASDAQ:BKNG', displayName: 'BKNG - Booking Holdings Inc.' },
                { name: 'NASDAQ:BKR', displayName: 'BKR - Baker Hughes Company' },
                { name: 'NASDAQ:CCEP', displayName: 'CCEP - Coca-Cola Europacific Partners plc' },
                { name: 'NASDAQ:CDNS', displayName: 'CDNS - Cadence Design Systems, Inc.' },
                { name: 'NASDAQ:CEG', displayName: 'CEG - Constellation Energy Corporation' },
                { name: 'NASDAQ:CMCSA', displayName: 'CMCSA - Comcast Corporation' },
                { name: 'NASDAQ:COST', displayName: 'COST - Costco Wholesale Corporation' },
                { name: 'NASDAQ:CPRT', displayName: 'CPRT - Copart, Inc.' },
                { name: 'NASDAQ:CRWD', displayName: 'CRWD - CrowdStrike Holdings, Inc.' },
                { name: 'NASDAQ:CRWV', displayName: 'CRWV - CoreWeave, Inc.' },
                { name: 'NASDAQ:CSCO', displayName: 'CSCO - Cisco Systems, Inc.' },
                { name: 'NASDAQ:CSX', displayName: 'CSX - CSX Corporation' },
                { name: 'NASDAQ:CTAS', displayName: 'CTAS - Cintas Corporation' },
                { name: 'NASDAQ:DASH', displayName: 'DASH - DoorDash, Inc.' },
                { name: 'NASDAQ:DDOG', displayName: 'DDOG - Datadog, Inc.' },
                { name: 'NASDAQ:DXCM', displayName: 'DXCM - DexCom, Inc.' },
                { name: 'NASDAQ:EXC', displayName: 'EXC - Exelon Corporation' },
                { name: 'NASDAQ:FANG', displayName: 'FANG - Diamondback Energy, Inc.' },
                { name: 'NASDAQ:FAST', displayName: 'FAST - Fastenal Company' },
                { name: 'NASDAQ:FER', displayName: 'FER - Ferrovial N.V.' },
                { name: 'NASDAQ:FTNT', displayName: 'FTNT - Fortinet, Inc.' },
                { name: 'NASDAQ:GEHC', displayName: 'GEHC - GE HealthCare Technologies Inc.' },
                { name: 'NASDAQ:GILD', displayName: 'GILD - Gilead Sciences, Inc.' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc.' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc.' },
                { name: 'NASDAQ:HON', displayName: 'HON - Honeywell International Inc.' },
                { name: 'NASDAQ:HONA', displayName: 'HONA - Honeywell Aerospace Inc.' },
                { name: 'NASDAQ:IDXX', displayName: 'IDXX - IDEXX Laboratories, Inc.' },
                { name: 'NASDAQ:INTC', displayName: 'INTC - Intel Corporation' },
                { name: 'NASDAQ:INTU', displayName: 'INTU - Intuit Inc.' },
                { name: 'NASDAQ:ISRG', displayName: 'ISRG - Intuitive Surgical, Inc.' },
                { name: 'NASDAQ:KDP', displayName: 'KDP - Keurig Dr Pepper Inc.' },
                { name: 'NASDAQ:KHC', displayName: 'KHC - The Kraft Heinz Company' },
                { name: 'NASDAQ:KLAC', displayName: 'KLAC - KLA Corporation' },
                { name: 'NASDAQ:LIN', displayName: 'LIN - Linde plc' },
                { name: 'NASDAQ:LITE', displayName: 'LITE - Lumentum Holdings Inc.' },
                { name: 'NASDAQ:LRCX', displayName: 'LRCX - Lam Research Corporation' },
                { name: 'NASDAQ:MAR', displayName: 'MAR - Marriott International' },
                { name: 'NASDAQ:MCHP', displayName: 'MCHP - Microchip Technology Incorporated' },
                { name: 'NASDAQ:MDLZ', displayName: 'MDLZ - Mondelez International, Inc.' },
                { name: 'NASDAQ:MELI', displayName: 'MELI - MercadoLibre, Inc.' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc.' },
                { name: 'NASDAQ:MNST', displayName: 'MNST - Monster Beverage Corporation' },
                { name: 'NASDAQ:MPWR', displayName: 'MPWR - Monolithic Power Systems, Inc.' },
                { name: 'NASDAQ:MRVL', displayName: 'MRVL - Marvell Technology, Inc.' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation' },
                { name: 'NASDAQ:MSTR', displayName: 'MSTR - Strategy Inc' },
                { name: 'NASDAQ:MU', displayName: 'MU - Micron Technology, Inc.' },
                { name: 'NASDAQ:NBIS', displayName: 'NBIS - Nebius Group N.V.' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc.' },
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation' },
                { name: 'NASDAQ:NXPI', displayName: 'NXPI - NXP Semiconductors N.V.' },
                { name: 'NASDAQ:ODFL', displayName: 'ODFL - Old Dominion Freight Line, Inc.' },
                { name: 'NASDAQ:ORLY', displayName: 'ORLY - O\'Reilly Automotive, Inc.' },
                { name: 'NASDAQ:PANW', displayName: 'PANW - Palo Alto Networks, Inc.' },
                { name: 'NASDAQ:PAYX', displayName: 'PAYX - Paychex, Inc.' },
                { name: 'NASDAQ:PCAR', displayName: 'PCAR - PACCAR Inc.' },
                { name: 'NASDAQ:PDD', displayName: 'PDD - PDD Holdings Inc.' },
                { name: 'NASDAQ:PEP', displayName: 'PEP - PepsiCo, Inc.' },
                { name: 'NASDAQ:PLTR', displayName: 'PLTR - Palantir Technologies Inc.' },
                { name: 'NASDAQ:PYPL', displayName: 'PYPL - PayPal Holdings, Inc.' },
                { name: 'NASDAQ:QCOM', displayName: 'QCOM - QUALCOMM Incorporated' },
                { name: 'NASDAQ:REGN', displayName: 'REGN - Regeneron Pharmaceuticals, Inc.' },
                { name: 'NASDAQ:RKLB', displayName: 'RKLB - Rocket Lab Corporation' },
                { name: 'NASDAQ:ROP', displayName: 'ROP - Roper Technologies, Inc.' },
                { name: 'NASDAQ:ROST', displayName: 'ROST - Ross Stores, Inc.' },
                { name: 'NASDAQ:SBUX', displayName: 'SBUX - Starbucks Corporation' },
                { name: 'NASDAQ:SHOP', displayName: 'SHOP - Shopify Inc.' },
                { name: 'NASDAQ:SNDK', displayName: 'SNDK - Sandisk Corporation' },
                { name: 'NASDAQ:SNPS', displayName: 'SNPS - Synopsys, Inc.' },
                { name: 'NASDAQ:SPCX', displayName: 'SPCX - Space Exploration Technologies Corp.' },
                { name: 'NASDAQ:STX', displayName: 'STX - Seagate Technology Holdings PLC' },
                { name: 'NASDAQ:TER', displayName: 'TER - Teradyne, Inc.' },
                { name: 'NASDAQ:TMUS', displayName: 'TMUS - T-Mobile US, Inc.' },
                { name: 'NASDAQ:TRI', displayName: 'TRI - Thomson Reuters Corporation Common Shares' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc.' },
                { name: 'NASDAQ:TTWO', displayName: 'TTWO - Take-Two Interactive Software, Inc.' },
                { name: 'NASDAQ:TXN', displayName: 'TXN - Texas Instruments Incorporated' },
                { name: 'NASDAQ:VRTX', displayName: 'VRTX - Vertex Pharmaceuticals Incorporated' },
                { name: 'NASDAQ:WBD', displayName: 'WBD - Warner Bros. Discovery, Inc.' },
                { name: 'NASDAQ:WDAY', displayName: 'WDAY - Workday, Inc.' },
                { name: 'NASDAQ:WDC', displayName: 'WDC - Western Digital Corporation' },
                { name: 'NASDAQ:WMT', displayName: 'WMT - Walmart Inc.' },
                { name: 'NASDAQ:XEL', displayName: 'XEL - Xcel Energy Inc.' },
            ],
        },
        {
            name: 'EWT',
            sourceUrl: 'https://stockanalysis.com/etf/ewt/holdings/',
            symbols: [
                { name: 'NYSE:TSM', displayName: 'TSM - Taiwan Semiconductor Manufacturing' },
                { name: 'NYSE:UMC', displayName: 'UMC - United Microelectronics Corp' },
                { name: 'NYSE:CHT', displayName: 'CHT - Chunghwa Telecom' },
                { name: 'NYSE:ASX', displayName: 'ASX - ASE Technology Holding' },
                { name: 'NASDAQ:HTHT', displayName: 'HTHT - Himax Technologies' },
            ],
        },
        {
            name: 'TSM',
            sourceUrl: 'https://www.quiverquant.com/etfholdings/',
            symbols: [
                { name: 'AMEX:VEU', displayName: 'VEU - Vanguard FTSE All-World ex-US ETF' },
                { name: 'NASDAQ:SMH', displayName: 'SMH - VanEck Semiconductor ETF' },
                { name: 'AMEX:CGGR', displayName: 'CGGR - Capital Group Growth ETF' },
                { name: 'NASDAQ:SOXX', displayName: 'SOXX - iShares Semiconductor ETF' },
                { name: 'AMEX:AVEM', displayName: 'AVEM - Avantis Emerging Markets Equity ETF' },
                { name: 'AMEX:DFAX', displayName: 'DFAX - Dimensional World ex U.S. Core Equity 2 ETF' },
                { name: 'AMEX:ARKK', displayName: 'ARKK - ARK Innovation ETF' },
                { name: 'AMEX:JGRO', displayName: 'JGRO - JPMorgan Active Growth ETF' },
                { name: 'NASDAQ:JGLO', displayName: 'JGLO - JPMorgan Global Equity ETF' },
                { name: 'NASDAQ:AIQ', displayName: 'AIQ - Global X Future Analytics Tech ETF' },
                { name: 'AMEX:TCAF', displayName: 'TCAF - T. Rowe Price Capital Appreciation Equity ETF' },
                { name: 'AMEX:FBCG', displayName: 'FBCG - Fidelity Blue Chip Growth ETF' },
                { name: 'AMEX:JAVA', displayName: 'JAVA - JPMorgan Active Value ETF' },
                { name: 'NASDAQ:TDIV', displayName: 'TDIV - First Trust NASDAQ Technology Dividend Index Fund' },
                { name: 'AMEX:CGDG', displayName: 'CGDG - Capital Group Dividend Growers ETF' },
                { name: 'AMEX:FRDM', displayName: 'FRDM - Alpha Architect Freedom 100 Emerging Market ETF' },
                { name: 'AMEX:SPGM', displayName: 'SPGM - SPDR Portfolio MSCI Global Stock Market ETF' },
                { name: 'AMEX:CGIE', displayName: 'CGIE - Capital Group International Equity ETF' },
                { name: 'AMEX:CWI', displayName: 'CWI - SPDR MSCI ACWI ex-US ETF' },
            ],
        },
    ],
};

export const NASDAQ100_TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'stock',
    width: '100%',
    height: '600',
};

export const NASDAQ100_TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'NASDAQ:NDX',
            title: 'Nasdaq 100 Index'
        },
        {
            proName: 'NASDAQ:IXIC',
            title: 'Nasdaq Composite'
        },
        {
            proName: 'NASDAQ:SMH',
            title: 'SMH'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
