// S&P 500 Page Configuration

export const MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'Technology',
            symbols: [
                { s: 'NASDAQ:NVDA', d: 'NVIDIA Corporation' },
                { s: 'NASDAQ:MSFT', d: 'Microsoft Corporation' },
                { s: 'NASDAQ:AAPL', d: 'Apple Inc' },
                { s: 'NASDAQ:AVGO', d: 'Broadcom Inc' },
                { s: 'NASDAQ:GOOGL', d: 'Alphabet Inc' },
                { s: 'NASDAQ:TSLA', d: 'Tesla Inc' },
                { s: 'NASDAQ:GOOG', d: 'Alphabet Inc' },
                { s: 'NYSE:ORCL', d: 'Oracle Corporation' },
                { s: 'NASDAQ:AMD', d: 'Advanced Micro Devices' },
            ],
        },
        {
            title: 'Finance',
            symbols: [
                { s: 'NYSE:BRK.B', d: 'Berkshire Hathaway Inc' },
                { s: 'NYSE:JPM', d: 'JPMorgan Chase & Co' },
                { s: 'NYSE:V', d: 'Visa Inc' },
                { s: 'NYSE:MA', d: 'Mastercard Incorporated' },
                { s: 'NYSE:BAC', d: 'Bank of America Corp' },
                { s: 'NYSE:WFC', d: 'Wells Fargo & Company' },
                { s: 'NYSE:GS', d: 'Goldman Sachs Group Inc' },
            ],
        },
        {
            title: 'Services',
            symbols: [
                { s: 'NASDAQ:AMZN', d: 'Amazon.com Inc' },
                { s: 'NASDAQ:META', d: 'Meta Platforms Inc' },
                { s: 'NASDAQ:NFLX', d: 'Netflix Inc' },
                { s: 'NYSE:DIS', d: 'Walt Disney Company' },
                { s: 'NASDAQ:GOOGL', d: 'Alphabet Inc' },
                { s: 'NASDAQ:PLTR', d: 'Palantir Technologies Inc' },
                { s: 'NYSE:ORCL', d: 'Oracle Corporation' },
            ],
        },
        {
            title: 'Consumer',
            symbols: [
                { s: 'NYSE:WMT', d: 'Walmart Inc' },
                { s: 'NASDAQ:COST', d: 'Costco Wholesale Corp' },
                { s: 'NYSE:HD', d: 'Home Depot Inc' },
                { s: 'NYSE:PG', d: 'Procter & Gamble Co' },
                { s: 'NYSE:MCD', d: 'McDonald\'s Corporation' },
                { s: 'NYSE:NKE', d: 'Nike Inc' },
                { s: 'NASDAQ:SBUX', d: 'Starbucks Corporation' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const HEATMAP_WIDGET_CONFIG = {
    dataSource: 'SPX500',
    blockSize: 'market_cap_basic',
    blockColor: 'change',
    grouping: 'sector',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const MARKET_DATA_WIDGET_CONFIG = {
    title: 'Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'Technology',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVIDIA Corporation' },
                { name: 'NASDAQ:MSFT', displayName: 'Microsoft Corporation' },
                { name: 'NASDAQ:AAPL', displayName: 'Apple Inc' },
                { name: 'NASDAQ:AVGO', displayName: 'Broadcom Inc' },
                { name: 'NASDAQ:GOOGL', displayName: 'Alphabet Inc' },
                { name: 'NASDAQ:TSLA', displayName: 'Tesla Inc' },
                { name: 'NASDAQ:GOOG', displayName: 'Alphabet Inc' },
                { name: 'NYSE:ORCL', displayName: 'Oracle Corporation' },
                { name: 'NASDAQ:AMD', displayName: 'Advanced Micro Devices' },
            ],
        },
        {
            name: 'Finance',
            symbols: [
                { name: 'NYSE:BRK.B', displayName: 'Berkshire Hathaway Inc' },
                { name: 'NYSE:JPM', displayName: 'JPMorgan Chase & Co' },
                { name: 'NYSE:V', displayName: 'Visa Inc' },
                { name: 'NYSE:MA', displayName: 'Mastercard Incorporated' },
                { name: 'NYSE:BAC', displayName: 'Bank of America Corp' },
                { name: 'NYSE:WFC', displayName: 'Wells Fargo & Company' },
                { name: 'NYSE:GS', displayName: 'Goldman Sachs Group Inc' },
            ],
        },
        {
            name: 'Services',
            symbols: [
                { name: 'NASDAQ:AMZN', displayName: 'Amazon.com Inc' },
                { name: 'NASDAQ:META', displayName: 'Meta Platforms Inc' },
                { name: 'NASDAQ:NFLX', displayName: 'Netflix Inc' },
                { name: 'NYSE:DIS', displayName: 'Walt Disney Company' },
                { name: 'NASDAQ:GOOGL', displayName: 'Alphabet Inc' },
                { name: 'NASDAQ:PLTR', displayName: 'Palantir Technologies Inc' },
                { name: 'NYSE:ORCL', displayName: 'Oracle Corporation' },
            ],
        },
        {
            name: 'Consumer',
            symbols: [
                { name: 'NYSE:WMT', displayName: 'Walmart Inc' },
                { name: 'NASDAQ:COST', displayName: 'Costco Wholesale Corp' },
                { name: 'NYSE:HD', displayName: 'Home Depot Inc' },
                { name: 'NYSE:PG', displayName: 'Procter & Gamble Co' },
                { name: 'NYSE:MCD', displayName: 'McDonald\'s Corporation' },
                { name: 'NYSE:NKE', displayName: 'Nike Inc' },
                { name: 'NASDAQ:SBUX', displayName: 'Starbucks Corporation' },
            ],
        },
    ],
};

export const TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'stock',
    width: '100%',
    height: '600',
};
