// S&P 500 Page Configuration

export const MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'ETF',
            symbols: [
                { s: 'AMEX:SPY', d: 'SPDR S&P 500 ETF Trust' },
                { s: 'AMEX:VOO', d: 'Vanguard S&P 500 ETF' },
                { s: 'AMEX:IVV', d: 'iShares Core S&P 500 ETF' },
                { s: 'AMEX:SPLG', d: 'SPDR Portfolio S&P 500 ETF' },
                { s: 'AMEX:SPYG', d: 'SPDR Portfolio S&P 500 Growth ETF' },
                { s: 'AMEX:SPYV', d: 'SPDR Portfolio S&P 500 Value ETF' },
            ],
        },
        {
            title: 'Technology',
            symbols: [
                { s: 'NASDAQ:NVDA', d: 'NVIDIA Corporation' },
                { s: 'NASDAQ:MSFT', d: 'Microsoft Corporation' },
                { s: 'NASDAQ:AAPL', d: 'Apple Inc' },
                { s: 'NASDAQ:AVGO', d: 'Broadcom Inc' },
                { s: 'NASDAQ:GOOGL', d: 'Alphabet Inc' },
                { s: 'NASDAQ:TSLA', d: 'Tesla Inc' },
                { s: 'NASDAQ:GOOG', d: 'Alphabet Inc' },
                { s: 'NYSE:ORCL', d: 'Oracle Corporation' },
                { s: 'NASDAQ:AMD', d: 'Advanced Micro Devices' },
            ],
        },
        {
            title: 'Finance',
            symbols: [
                { s: 'NYSE:BRK.B', d: 'Berkshire Hathaway Inc' },
                { s: 'NYSE:JPM', d: 'JPMorgan Chase & Co' },
                { s: 'NYSE:V', d: 'Visa Inc' },
                { s: 'NYSE:MA', d: 'Mastercard Incorporated' },
                { s: 'NYSE:BAC', d: 'Bank of America Corp' },
                { s: 'NYSE:WFC', d: 'Wells Fargo & Company' },
                { s: 'NYSE:GS', d: 'Goldman Sachs Group Inc' },
            ],
        },
        {
            title: 'Services',
            symbols: [
                { s: 'NASDAQ:AMZN', d: 'Amazon.com Inc' },
                { s: 'NASDAQ:META', d: 'Meta Platforms Inc' },
                { s: 'NASDAQ:NFLX', d: 'Netflix Inc' },
                { s: 'NYSE:DIS', d: 'Walt Disney Company' },
                { s: 'NASDAQ:GOOGL', d: 'Alphabet Inc' },
                { s: 'NASDAQ:PLTR', d: 'Palantir Technologies Inc' },
                { s: 'NYSE:ORCL', d: 'Oracle Corporation' },
            ],
        },
        {
            title: 'Consumer',
            symbols: [
                { s: 'NYSE:WMT', d: 'Walmart Inc' },
                { s: 'NASDAQ:COST', d: 'Costco Wholesale Corp' },
                { s: 'NYSE:HD', d: 'Home Depot Inc' },
                { s: 'NYSE:PG', d: 'Procter & Gamble Co' },
                { s: 'NYSE:MCD', d: 'McDonald\'s Corporation' },
                { s: 'NYSE:NKE', d: 'Nike Inc' },
                { s: 'NASDAQ:SBUX', d: 'Starbucks Corporation' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const HEATMAP_WIDGET_CONFIG = {
    dataSource: 'SPX500',
    blockSize: 'market_cap_basic',
    blockColor: 'change',
    grouping: 'sector',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const MARKET_DATA_WIDGET_CONFIG = {
    title: 'S&P 500 Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'SPY',
            sourceUrl: 'https://stockanalysis.com/etf/spy/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation (7.75%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (6.73%)' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (6.49%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.70%)' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc. (2.85%)' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc. (2.71%)' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc. (2.52%)' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc. (2.12%)' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc. (2.03%)' },
                { name: 'NYSE:BRK.B', displayName: 'BRK.B - Berkshire Hathaway Inc. (1.60%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (1.46%)' },
                { name: 'NYSE:LLY', displayName: 'LLY - Eli Lilly and Company (1.14%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (1.04%)' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc. (0.91%)' },
                { name: 'NYSE:ORCL', displayName: 'ORCL - Oracle Corporation (0.87%)' },
                { name: 'NYSE:XOM', displayName: 'XOM - Exxon Mobil Corporation (0.84%)' },
                { name: 'NYSE:WMT', displayName: 'WMT - Walmart Inc. (0.83%)' },
                { name: 'NYSE:MA', displayName: 'MA - Mastercard Incorporated (0.83%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (0.81%)' },
                { name: 'NASDAQ:COST', displayName: 'COST - Costco Wholesale Corporation (0.74%)' },
                { name: 'NASDAQ:PLTR', displayName: 'PLTR - Palantir Technologies Inc. (0.72%)' },
                { name: 'NYSE:ABBV', displayName: 'ABBV - AbbVie Inc. (0.71%)' },
                { name: 'NYSE:HD', displayName: 'HD - The Home Depot, Inc. (0.68%)' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices, Inc. (0.62%)' },
                { name: 'NYSE:PG', displayName: 'PG - The Procter & Gamble Company (0.62%)' },
            ],
        },
        {
            name: 'SPYG',
            sourceUrl: 'https://stockanalysis.com/etf/spyg/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation (14.19%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (6.41%)' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (5.46%)' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc. (5.23%)' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc. (4.97%)' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc. (4.61%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.94%)' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc. (3.89%)' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc. (3.71%)' },
                { name: 'NYSE:LLY', displayName: 'LLY - Eli Lilly and Company (2.09%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (1.91%)' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc. (1.67%)' },
            ],
        },
        {
            name: 'SPYV',
            sourceUrl: 'https://stockanalysis.com/etf/spyv/holdings/',
            symbols: [
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (7.70%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (7.11%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.42%)' },
                { name: 'NYSE:XOM', displayName: 'XOM - Exxon Mobil Corporation (1.86%)' },
                { name: 'NYSE:BRK.B', displayName: 'BRK.B - Berkshire Hathaway Inc. (1.80%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (1.78%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (1.39%)' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices, Inc. (1.37%)' },
                { name: 'NYSE:PG', displayName: 'PG - The Procter & Gamble Company (1.36%)' },
            ],
        },
    ],
};

export const TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'stock',
    width: '100%',
    height: '600',
};

export const TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'FOREXCOM:SPXUSD',
            title: 'S&P 500'
        },
        {
            proName: 'CAPITALCOM:DXY',
            title: 'U.S. Dollar Index'
        }, 
        {
            proName: 'BATS:VIXY',
            title: 'VIXY'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
