// S&P 500 Page Configuration

export const MARKET_OVERVIEW_WIDGET_CONFIG = {
    colorTheme: 'dark',
    dateRange: '12M',
    locale: 'en',
    largeChartUrl: '',
    isTransparent: true,
    showFloatingTooltip: true,
    plotLineColorGrowing: '#0FEDBE',
    plotLineColorFalling: '#0FEDBE',
    gridLineColor: 'rgba(240, 243, 250, 0)',
    scaleFontColor: '#DBDBDB',
    belowLineFillColorGrowing: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorFalling: 'rgba(41, 98, 255, 0.12)',
    belowLineFillColorGrowingBottom: 'rgba(41, 98, 255, 0)',
    belowLineFillColorFallingBottom: 'rgba(41, 98, 255, 0)',
    symbolActiveColor: 'rgba(15, 237, 190, 0.05)',
    tabs: [
        {
            title: 'ETF',
            symbols: [
                { s: 'AMEX:SPY', d: 'SPDR S&P 500 ETF Trust' },
                { s: 'AMEX:VOO', d: 'Vanguard S&P 500 ETF' },
                { s: 'AMEX:IVV', d: 'iShares Core S&P 500 ETF' },
                { s: 'AMEX:SPLG', d: 'SPDR Portfolio S&P 500 ETF' },
                { s: 'AMEX:SPYG', d: 'SPDR Portfolio S&P 500 Growth ETF' },
                { s: 'AMEX:SPYV', d: 'SPDR Portfolio S&P 500 Value ETF' },
            ],
        },
        {
            title: 'Finance',
            symbols: [
                { s: 'NYSE:BRK.B', d: 'Berkshire Hathaway Inc' },
                { s: 'NYSE:JPM', d: 'JPMorgan Chase & Co' },
                { s: 'NYSE:V', d: 'Visa Inc' },
                { s: 'NYSE:MA', d: 'Mastercard Incorporated' },
                { s: 'NYSE:BAC', d: 'Bank of America Corp' },
                { s: 'NYSE:WFC', d: 'Wells Fargo & Company' },
                { s: 'NYSE:GS', d: 'Goldman Sachs Group Inc' },
            ],
        },
        {
            title: 'Health',
            symbols: [
                { s: 'NYSE:LLY', d: 'Eli Lilly and Company' },
                { s: 'NYSE:ABBV', d: 'AbbVie Inc' },
                { s: 'NYSE:TMO', d: 'Thermo Fisher Scientific Inc' },
                { s: 'NASDAQ:ISRG', d: 'Intuitive Surgical Inc' },
                { s: 'NASDAQ:AMGN', d: 'Amgen Inc' },
                { s: 'NYSE:DHR', d: 'Danaher Corporation' },
                { s: 'NYSE:ABT', d: 'Abbott Laboratories' },
                { s: 'NYSE:BSX', d: 'Boston Scientific Corporation' },
                { s: 'NYSE:PFE', d: 'Pfizer Inc' },
                { s: 'NYSE:BMY', d: 'Bristol-Myers Squibb Company' },
                { s: 'NYSE:ZTS', d: 'Zoetis Inc' },
                { s: 'NASDAQ:REGN', d: 'Regeneron Pharmaceuticals Inc' },
                { s: 'NYSE:JNJ', d: 'Johnson & Johnson' },
                { s: 'NYSE:MRK', d: 'Merck & Co Inc' },
                { s: 'NASDAQ:GILD', d: 'Gilead Sciences Inc' },
                { s: 'NYSE:SYK', d: 'Stryker Corporation' },
                { s: 'NYSE:MDT', d: 'Medtronic plc' },
                { s: 'NASDAQ:VRTX', d: 'Vertex Pharmaceuticals Inc' },
            ],
        },
        {
            title: 'Retail',
            symbols: [
                { s: 'NASDAQ:AMZN', d: 'Amazon.com Inc' },
                { s: 'NYSE:WMT', d: 'Walmart Inc' },
                { s: 'NASDAQ:COST', d: 'Costco Wholesale Corp' },
                { s: 'NYSE:HD', d: 'Home Depot Inc' },
                { s: 'NYSE:TJX', d: 'TJX Companies Inc' },
                { s: 'NYSE:CVS', d: 'CVS Health Corporation' },
                { s: 'NASDAQ:ORLY', d: "O'Reilly Automotive Inc" },
                { s: 'NYSE:AZO', d: 'AutoZone Inc' },
                { s: 'NYSE:LOW', d: "Lowe's Companies Inc" },
                { s: 'NYSE:KR', d: 'Kroger Co' },
                { s: 'NASDAQ:ROST', d: 'Ross Stores Inc' },
                { s: 'NASDAQ:EBAY', d: 'eBay Inc' },
                { s: 'NASDAQ:CPRT', d: 'Copart Inc' },
            ],
        },
        {
            title: 'Consumer',
            symbols: [
                { s: 'NYSE:MCD', d: "McDonald's Corporation" },
                { s: 'NYSE:DIS', d: 'Walt Disney Company' },
                { s: 'NASDAQ:BKNG', d: 'Booking Holdings Inc' },
                { s: 'NYSE:RCL', d: 'Royal Caribbean Cruises Ltd' },
                { s: 'NASDAQ:ABNB', d: 'Airbnb Inc' },
                { s: 'NASDAQ:CTAS', d: 'Cintas Corporation' },
                { s: 'NASDAQ:CMCSA', d: 'Comcast Corporation' },
                { s: 'NASDAQ:SBUX', d: 'Starbucks Corporation' },
                { s: 'NASDAQ:MAR', d: 'Marriott International Inc' },
                { s: 'NYSE:HLT', d: 'Hilton Worldwide Holdings Inc' },
                { s: 'NYSE:CMG', d: 'Chipotle Mexican Grill Inc' },
                { s: 'NYSE:LYV', d: 'Live Nation Entertainment Inc' },
                { s: 'NASDAQ:WBD', d: 'Warner Bros. Discovery Inc' },
                { s: 'NYSE:YUM', d: 'Yum! Brands Inc' },
                { s: 'NYSE:CCL', d: 'Carnival Corporation' },
                { s: 'NASDAQ:CHTR', d: 'Charter Communications Inc' },
                { s: 'NYSE:LVS', d: 'Las Vegas Sands Corp' },
                { s: 'NASDAQ:EXPE', d: 'Expedia Group Inc' },
                { s: 'NASDAQ:FOX', d: 'Fox Corporation' },
                { s: 'NASDAQ:FOXA', d: 'Fox Corporation' },
                { s: 'NYSE:TKO', d: 'TKO Group Holdings Inc' },
            ],
        },
        {
            title: 'Producer',
            symbols: [
                { s: 'NYSE:CAT', d: 'Caterpillar Inc' },
                { s: 'NASDAQ:AMAT', d: 'Applied Materials Inc' },
                { s: 'NYSE:DE', d: 'Deere & Company' },
                { s: 'NYSE:MMM', d: '3M Company' },
                { s: 'NYSE:ITW', d: 'Illinois Tool Works Inc' },
                { s: 'NYSE:JCI', d: 'Johnson Controls International plc' },
                { s: 'NYSE:GEV', d: 'GE Vernova Inc' },
                { s: 'NYSE:PH', d: 'Parker-Hannifin Corporation' },
                { s: 'NYSE:CMI', d: 'Cummins Inc' },
                { s: 'NASDAQ:LRCX', d: 'Lam Research Corporation' },
                { s: 'NYSE:ETN', d: 'Eaton Corporation plc' },
                { s: 'NYSE:TT', d: 'Trane Technologies plc' },
                { s: 'NYSE:AME', d: 'AMETEK Inc' },
                { s: 'NYSE:ROK', d: 'Rockwell Automation Inc' },
                { s: 'NYSE:XYL', d: 'Xylem Inc' },
                { s: 'NASDAQ:PCAR', d: 'PACCAR Inc' },
                { s: 'NYSE:WAB', d: 'Westinghouse Air Brake Technologies Corp' },
                { s: 'NYSE:CARR', d: 'Carrier Global Corporation' },
            ],
        },
    ],
    support_host: 'https://www.tradingview.com',
    backgroundColor: '#141414',
    width: '100%',
    height: 600,
    showSymbolLogo: true,
    showChart: true,
};

export const HEATMAP_WIDGET_CONFIG = {
    dataSource: 'SPX500',
    blockSize: 'market_cap_basic',
    blockColor: 'change',
    grouping: 'sector',
    isTransparent: true,
    locale: 'en',
    symbolUrl: '',
    colorTheme: 'dark',
    exchanges: [],
    hasTopBar: false,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: '100%',
    height: '600',
};

export const MARKET_DATA_WIDGET_CONFIG = {
    title: 'S&P 500 Stocks',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'SPY',
            sourceUrl: 'https://stockanalysis.com/etf/spy/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation (8.34%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (6.85%)' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (6.79%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.78%)' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc. (2.98%)' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc. (2.77%)' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc. (2.65%)' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc. (2.20%)' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc. (2.13%)' },
                { name: 'NYSE:BRK.B', displayName: 'BRK.B - Berkshire Hathaway Inc. (1.50%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (1.43%)' },
                { name: 'NYSE:LLY', displayName: 'LLY - Eli Lilly and Company (1.11%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (1.00%)' },
                { name: 'NYSE:XOM', displayName: 'XOM - Exxon Mobil Corporation (0.83%)' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc. (0.80%)' },
                { name: 'NYSE:MA', displayName: 'MA - Mastercard Incorporated (0.79%)' },
                { name: 'NYSE:ORCL', displayName: 'ORCL - Oracle Corporation (0.79%)' },
                { name: 'NYSE:WMT', displayName: 'WMT - Walmart Inc. (0.77%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (0.77%)' },
                { name: 'NASDAQ:PLTR', displayName: 'PLTR - Palantir Technologies Inc. (0.73%)' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices, Inc. (0.71%)' },
                { name: 'NASDAQ:COST', displayName: 'COST - Costco Wholesale Corporation (0.70%)' },
                { name: 'NYSE:ABBV', displayName: 'ABBV - AbbVie Inc. (0.68%)' },
                { name: 'NYSE:HD', displayName: 'HD - The Home Depot, Inc. (0.65%)' },
                { name: 'NYSE:BAC', displayName: 'BAC - Bank of America Corporation (0.61%)' },
            ],
        },
        {
            name: 'SPYG',
            sourceUrl: 'https://stockanalysis.com/etf/spyg/holdings/',
            symbols: [
                { name: 'NASDAQ:NVDA', displayName: 'NVDA - NVIDIA Corporation (14.19%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (6.41%)' },
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (5.46%)' },
                { name: 'NASDAQ:AVGO', displayName: 'AVGO - Broadcom Inc. (5.23%)' },
                { name: 'NASDAQ:META', displayName: 'META - Meta Platforms, Inc. (4.97%)' },
                { name: 'NASDAQ:GOOGL', displayName: 'GOOGL - Alphabet Inc. (4.61%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.94%)' },
                { name: 'NASDAQ:TSLA', displayName: 'TSLA - Tesla, Inc. (3.89%)' },
                { name: 'NASDAQ:GOOG', displayName: 'GOOG - Alphabet Inc. (3.71%)' },
                { name: 'NYSE:LLY', displayName: 'LLY - Eli Lilly and Company (2.09%)' },
                { name: 'NYSE:V', displayName: 'V - Visa Inc. (1.91%)' },
                { name: 'NASDAQ:NFLX', displayName: 'NFLX - Netflix, Inc. (1.67%)' },
            ],
        },
        {
            name: 'SPYV',
            sourceUrl: 'https://stockanalysis.com/etf/spyv/holdings/',
            symbols: [
                { name: 'NASDAQ:AAPL', displayName: 'AAPL - Apple Inc. (7.70%)' },
                { name: 'NASDAQ:MSFT', displayName: 'MSFT - Microsoft Corporation (7.11%)' },
                { name: 'NASDAQ:AMZN', displayName: 'AMZN - Amazon.com, Inc. (3.42%)' },
                { name: 'NYSE:XOM', displayName: 'XOM - Exxon Mobil Corporation (1.86%)' },
                { name: 'NYSE:BRK.B', displayName: 'BRK.B - Berkshire Hathaway Inc. (1.80%)' },
                { name: 'NYSE:JNJ', displayName: 'JNJ - Johnson & Johnson (1.78%)' },
                { name: 'NYSE:JPM', displayName: 'JPM - JPMorgan Chase & Co. (1.39%)' },
                { name: 'NASDAQ:AMD', displayName: 'AMD - Advanced Micro Devices, Inc. (1.37%)' },
                { name: 'NYSE:PG', displayName: 'PG - The Procter & Gamble Company (1.36%)' },
            ],
        },
    ],
};

export const TOP_STORIES_WIDGET_CONFIG = {
    displayMode: 'regular',
    feedMode: 'market',
    colorTheme: 'dark',
    isTransparent: true,
    locale: 'en',
    market: 'stock',
    width: '100%',
    height: '600',
};

export const TICKER_TAPE_WIDGET_CONFIG = {
    symbols: [
        {
            proName: 'FOREXCOM:SPXUSD',
            title: 'S&P 500'
        },
        {
            proName: 'CAPITALCOM:DXY',
            title: 'U.S. Dollar Index'
        }, 
        {
            proName: 'BATS:VIXY',
            title: 'VIXY'
        },
    ],
    showSymbolLogo: true,
    isTransparent: true,
    displayMode: 'adaptive',
    colorTheme: 'dark',
    locale: 'en',
    width: '100%',
    height: 46,
};
