// Watchlist Page Configuration

export const WATCHLIST_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Popular ETFs',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'ARK Invest',
            sourceUrl: 'https://www.ark-funds.com/',
            symbols: [
                { name: 'AMEX:ARKK', displayName: 'ARKK - ARK Innovation ETF' },
                { name: 'AMEX:ARKG', displayName: 'ARKG - ARK Genomic Revolution ETF' },
                { name: 'AMEX:ARKW', displayName: 'ARKW - ARK Next Generation Internet ETF' },
                { name: 'AMEX:ARKF', displayName: 'ARKF - ARK Fintech Innovation ETF' },
                { name: 'AMEX:ARKQ', displayName: 'ARKQ - ARK Autonomous Technology & Robotics ETF' },
                { name: 'AMEX:ARKX', displayName: 'ARKX - ARK Space Exploration & Innovation ETF' },
            ],
        },
        {
            name: 'First Trust',
            sourceUrl: 'https://www.ftportfolios.com/',
            symbols: [
                { name: 'NASDAQ:FTDS', displayName: 'FTDS - First Trust Dividend Strength ETF' },
                { name: 'AMEX:FDL', displayName: 'FDL - First Trust Morningstar Dividend Leaders Index Fund' },
                { name: 'AMEX:FRI', displayName: 'FRI - First Trust S&P REIT Index Fund' },
                { name: 'AMEX:FCG', displayName: 'FCG - First Trust Natural Gas ETF' },
                { name: 'AMEX:FIW', displayName: 'FIW - First Trust Water ETF' },
                { name: 'AMEX:FAN', displayName: 'FAN - First Trust Global Wind Energy ETF' },
            ],
        },
        {
            name: 'iShares',
            sourceUrl: 'https://www.ishares.com/',
            symbols: [
                { name: 'AMEX:EFA', displayName: 'EFA - iShares MSCI EAFE ETF' },
                { name: 'AMEX:EXI', displayName: 'EXI - iShares Global Industrials ETF' },
                { name: 'AMEX:IAU', displayName: 'IAU - iShares Gold Trust' },
                { name: 'NASDAQ:IBIT', displayName: 'IBIT - iShares Bitcoin Trust ETF' },
                { name: 'AMEX:IDU', displayName: 'IDU - iShares U.S. Utilities ETF' },
                { name: 'AMEX:IEFA', displayName: 'IEFA - iShares Core MSCI EAFE ETF' },
                { name: 'AMEX:IEMG', displayName: 'IEMG - iShares Core MSCI Emerging Markets ETF' },
                { name: 'AMEX:IJH', displayName: 'IJH - iShares Core S&P Mid-Cap ETF' },
                { name: 'AMEX:IJR', displayName: 'IJR - iShares Core S&P Small-Cap ETF' },
                { name: 'AMEX:ITOT', displayName: 'ITOT - iShares Core S&P Total U.S. Stock Market ETF' },
                { name: 'AMEX:IVE', displayName: 'IVE - iShares S&P 500 Value ETF' },
                { name: 'AMEX:IVV', displayName: 'IVV - iShares Core S&P 500 ETF' },
                { name: 'AMEX:IVW', displayName: 'IVW - iShares S&P 500 Growth ETF' },
                { name: 'AMEX:IWB', displayName: 'IWB - iShares Russell 1000 ETF' },
                { name: 'AMEX:IWD', displayName: 'IWD - iShares Russell 1000 Value ETF' },
                { name: 'AMEX:IWF', displayName: 'IWF - iShares Russell 1000 Growth ETF' },
                { name: 'AMEX:IWM', displayName: 'IWM - iShares Russell 2000 ETF' },
                { name: 'AMEX:IWR', displayName: 'IWR - iShares Russell Midcap ETF' },
                { name: 'AMEX:IXC', displayName: 'IXC - iShares Global Energy ETF' },
                { name: 'AMEX:IXG', displayName: 'IXG - iShares Global Financials ETF' },
                { name: 'AMEX:IXJ', displayName: 'IXJ - iShares Global Healthcare ETF' },
                { name: 'AMEX:IXN', displayName: 'IXN - iShares Global Tech ETF' },
                { name: 'AMEX:IXP', displayName: 'IXP - iShares Global Comm Services ETF' },
                { name: 'NASDAQ:IXUS', displayName: 'IXUS - iShares Core MSCI Total International Stock ETF' },
                { name: 'AMEX:IYC', displayName: 'IYC - iShares U.S. Consumer Discretionary ETF' },
                { name: 'AMEX:IYE', displayName: 'IYE - iShares U.S. Energy ETF' },
                { name: 'AMEX:IYF', displayName: 'IYF - iShares U.S. Financials ETF' },
                { name: 'AMEX:IYH', displayName: 'IYH - iShares U.S. Healthcare ETF' },
                { name: 'AMEX:IYJ', displayName: 'IYJ - iShares U.S. Industrials ETF' },
                { name: 'AMEX:IYK', displayName: 'IYK - iShares U.S. Consumer Staples ETF' },
                { name: 'AMEX:IYM', displayName: 'IYM - iShares U.S. Basic Materials ETF' },
                { name: 'AMEX:IYR', displayName: 'IYR - iShares U.S. Real Estate ETF' },
                { name: 'AMEX:IYW', displayName: 'IYW - iShares U.S. Technology ETF' },
                { name: 'AMEX:JXI', displayName: 'JXI - iShares Global Utilities ETF' },
                { name: 'AMEX:KXI', displayName: 'KXI - iShares Global Consumer Staples ETF' },
                { name: 'AMEX:MXI', displayName: 'MXI - iShares Global Materials ETF' },
                { name: 'AMEX:REET', displayName: 'REET - iShares Global REIT ETF' },
                { name: 'AMEX:RXI', displayName: 'RXI - iShares Global Consumer Discretionary ETF' },
            ],
        },
        {
            name: 'J.P. Morgan',
            sourceUrl: 'https://am.jpmorgan.com/',
            symbols: [
                { name: 'AMEX:JEPI', displayName: 'JEPI - JPMorgan Equity Premium Income ETF' },
                { name: 'NASDAQ:JEPQ', displayName: 'JEPQ - JPMorgan Nasdaq Equity Premium Income ETF' },
                { name: 'AMEX:JPST', displayName: 'JPST - JPMorgan Ultra-Short Income ETF' },
                { name: 'AMEX:JMUB', displayName: 'JMUB - JPMorgan Municipal ETF' },
                { name: 'AMEX:JPUS', displayName: 'JPUS - JPMorgan Diversified Return U.S. Equity ETF' },
                { name: 'AMEX:JPIE', displayName: 'JPIE - JPMorgan Income ETF' },
                { name: 'AMEX:JPLD', displayName: 'JPLD - JPMorgan U.S. Value Factor ETF' },
            ],
        },
        {
            name: 'Invesco',
            sourceUrl: 'https://www.invesco.com/',
            symbols: [
                { name: 'NASDAQ:QQQ', displayName: 'QQQ - Invesco QQQ Trust' },
                { name: 'NASDAQ:QQQM', displayName: 'QQQM - Invesco NASDAQ 100 ETF' },
                { name: 'NASDAQ:PTF', displayName: 'PTF - Invesco DWA Technology Momentum ETF' },
                { name: 'NASDAQ:PFI', displayName: 'PFI - Invesco DWA Financial Momentum ETF' },
                { name: 'AMEX:PXE', displayName: 'PXE - Invesco DWA Energy Momentum ETF' },
                { name: 'NASDAQ:PTH', displayName: 'PTH - Invesco DWA Healthcare Momentum ETF' },
                { name: 'NASDAQ:PRN', displayName: 'PRN - Invesco DWA Industrials Momentum ETF' },
                { name: 'NASDAQ:PSL', displayName: 'PSL - Invesco DWA Consumer Staples Momentum ETF' },
                { name: 'NASDAQ:PEZ', displayName: 'PEZ - Invesco DWA Consumer Cyclicals Momentum ETF' },
                { name: 'NASDAQ:PYZ', displayName: 'PYZ - Invesco DWA Basic Materials Momentum ETF' },
                { name: 'AMEX:PSR', displayName: 'PSR - Invesco Active U.S. Real Estate ETF' },
                { name: 'NASDAQ:PUI', displayName: 'PUI - Invesco DWA Utilities Momentum ETF' },
                { name: 'NASDAQ:PXI', displayName: 'PXI - Invesco DWA Communication Services Momentum ETF' },
            ],
        },
        {
            name: 'Schwab',
            sourceUrl: 'https://www.schwabassetmanagement.com/',
            symbols: [
                { name: 'AMEX:SCHD', displayName: 'SCHD - Schwab US Dividend Equity ETF' },
                { name: 'AMEX:SCHX', displayName: 'SCHX - Schwab U.S. Large-Cap ETF' },
                { name: 'AMEX:SCHG', displayName: 'SCHG - Schwab U.S. Large-Cap Growth ETF' },
                { name: 'AMEX:SCHF', displayName: 'SCHF - Schwab International Equity ETF' },
                { name: 'AMEX:SCHA', displayName: 'SCHA - Schwab U.S. Small-Cap ETF' },
                { name: 'AMEX:SCHB', displayName: 'SCHB - Schwab U.S. Broad Market ETF' },
            ],
        },
        {
            name: 'SPDR',
            sourceUrl: 'https://www.ssga.com/us/en/intermediary/etfs',
            symbols: [
                { name: 'AMEX:SPY', displayName: 'SPY - SPDR S&P 500 ETF Trust' },
                { name: 'AMEX:SPLG', displayName: 'SPLG - SPDR Portfolio S&P 500 ETF' },
                { name: 'AMEX:SPYG', displayName: 'SPYG - SPDR Portfolio S&P 500 Growth ETF' },
                { name: 'AMEX:GLD', displayName: 'GLD - SPDR Gold Shares' },
                { name: 'AMEX:XLK', displayName: 'XLK - Technology Select Sector SPDR Fund' },
                { name: 'AMEX:XLF', displayName: 'XLF - Financial Select Sector SPDR Fund' },
                { name: 'AMEX:XLE', displayName: 'XLE - Energy Select Sector SPDR Fund' },
                { name: 'AMEX:XLV', displayName: 'XLV - Health Care Select Sector SPDR Fund' },
                { name: 'AMEX:XLI', displayName: 'XLI - Industrial Select Sector SPDR Fund' },
                { name: 'AMEX:XLP', displayName: 'XLP - Consumer Staples Select Sector SPDR Fund' },
                { name: 'AMEX:XLY', displayName: 'XLY - Consumer Discretionary Select Sector SPDR Fund' },
                { name: 'AMEX:XLB', displayName: 'XLB - Materials Select Sector SPDR Fund' },
                { name: 'AMEX:XLRE', displayName: 'XLRE - Real Estate Select Sector SPDR Fund' },
                { name: 'AMEX:XLU', displayName: 'XLU - Utilities Select Sector SPDR Fund' },
                { name: 'AMEX:XLC', displayName: 'XLC - Communication Services Select Sector SPDR Fund' },
            ],
        },
        {
            name: 'Vanguard',
            sourceUrl: 'https://investor.vanguard.com/',
            symbols: [
                { name: 'AMEX:VTI', displayName: 'VTI - Vanguard Total Stock Market ETF' },
                { name: 'AMEX:VOO', displayName: 'VOO - Vanguard S&P 500 ETF' },
                { name: 'AMEX:VUG', displayName: 'VUG - Vanguard Growth ETF' },
                { name: 'AMEX:VTV', displayName: 'VTV - Vanguard Value ETF' },
                { name: 'AMEX:VV', displayName: 'VV - Vanguard Large-Cap ETF' },
                { name: 'AMEX:VIG', displayName: 'VIG - Vanguard Dividend Appreciation ETF' },
                { name: 'AMEX:VYM', displayName: 'VYM - Vanguard High Dividend Yield Index ETF' },
                { name: 'AMEX:VB', displayName: 'VB - Vanguard Small-Cap ETF' },
                { name: 'AMEX:VO', displayName: 'VO - Vanguard Mid-Cap ETF' },
                { name: 'AMEX:VT', displayName: 'VT - Vanguard Total World Stock ETF' },
                { name: 'NASDAQ:VTWO', displayName: 'VTWO - Vanguard Russell 2000 ETF' },
                { name: 'NASDAQ:VXUS', displayName: 'VXUS - Vanguard Total International Stock ETF' },
                { name: 'AMEX:VEA', displayName: 'VEA - Vanguard FTSE Developed Markets ETF' },
                { name: 'AMEX:VWO', displayName: 'VWO - Vanguard FTSE Emerging Markets ETF' },
                { name: 'AMEX:VEU', displayName: 'VEU - Vanguard FTSE All-World ex-US ETF' },
                { name: 'AMEX:VGT', displayName: 'VGT - Vanguard Information Technology ETF' },
                { name: 'AMEX:VFH', displayName: 'VFH - Vanguard Financials ETF' },
                { name: 'AMEX:VDE', displayName: 'VDE - Vanguard Energy ETF' },
                { name: 'AMEX:VHT', displayName: 'VHT - Vanguard Health Care ETF' },
                { name: 'AMEX:VIS', displayName: 'VIS - Vanguard Industrials ETF' },
                { name: 'AMEX:VDC', displayName: 'VDC - Vanguard Consumer Staples ETF' },
                { name: 'AMEX:VCR', displayName: 'VCR - Vanguard Consumer Discretionary ETF' },
                { name: 'AMEX:VAW', displayName: 'VAW - Vanguard Materials ETF' },
                { name: 'AMEX:VNQ', displayName: 'VNQ - Vanguard Real Estate ETF' },
                { name: 'AMEX:VPU', displayName: 'VPU - Vanguard Utilities ETF' },
                { name: 'AMEX:VOX', displayName: 'VOX - Vanguard Communication Services ETF' },
            ],
        },
    ],
};
