// Watchlist Page Configuration

export const WATCHLIST_MARKET_DATA_WIDGET_CONFIG = {
    title: 'Popular ETFs',
    width: '100%',
    height: 600,
    locale: 'en',
    showSymbolLogo: true,
    colorTheme: 'dark',
    isTransparent: false,
    backgroundColor: '#0F0F0F',
    symbolsGroups: [
        {
            name: 'ARK Invest',
            sourceUrl: 'https://www.ark-funds.com/',
            symbols: [
                { name: 'AMEX:ARKK', displayName: 'ARKK - ARK Innovation ETF' },
                { name: 'AMEX:ARKG', displayName: 'ARKG - ARK Genomic Revolution ETF' },
                { name: 'AMEX:ARKW', displayName: 'ARKW - ARK Next Generation Internet ETF' },
                { name: 'AMEX:ARKF', displayName: 'ARKF - ARK Fintech Innovation ETF' },
                { name: 'AMEX:ARKQ', displayName: 'ARKQ - ARK Autonomous Technology & Robotics ETF' },
                { name: 'AMEX:ARKX', displayName: 'ARKX - ARK Space Exploration & Innovation ETF' },
            ],
        },
        {
            name: 'First Trust',
            sourceUrl: 'https://www.ftportfolios.com/',
            symbols: [
                { name: 'NASDAQ:FTDS', displayName: 'FTDS - First Trust Dividend Strength ETF' },
                { name: 'AMEX:FDL', displayName: 'FDL - First Trust Morningstar Dividend Leaders Index Fund' },
                { name: 'AMEX:FRI', displayName: 'FRI - First Trust S&P REIT Index Fund' },
                { name: 'AMEX:FCG', displayName: 'FCG - First Trust Natural Gas ETF' },
                { name: 'AMEX:FIW', displayName: 'FIW - First Trust Water ETF' },
                { name: 'AMEX:FAN', displayName: 'FAN - First Trust Global Wind Energy ETF' },
            ],
        },
        {
            name: 'iShares',
            sourceUrl: 'https://www.ishares.com/',
            symbols: [
                { name: 'AMEX:IVV', displayName: 'IVV - iShares Core S&P 500 ETF' },
                { name: 'AMEX:IWM', displayName: 'IWM - iShares Russell 2000 ETF' },
                { name: 'AMEX:IEFA', displayName: 'IEFA - iShares Core MSCI EAFE ETF' },
                { name: 'AMEX:IEMG', displayName: 'IEMG - iShares Core MSCI Emerging Markets ETF' },
                { name: 'AMEX:IYW', displayName: 'IYW - iShares U.S. Technology ETF' },
                { name: 'AMEX:IYF', displayName: 'IYF - iShares U.S. Financials ETF' },
                { name: 'AMEX:IYE', displayName: 'IYE - iShares U.S. Energy ETF' },
                { name: 'AMEX:IYH', displayName: 'IYH - iShares U.S. Healthcare ETF' },
                { name: 'AMEX:IYJ', displayName: 'IYJ - iShares U.S. Industrials ETF' },
                { name: 'AMEX:IYK', displayName: 'IYK - iShares U.S. Consumer Staples ETF' },
                { name: 'AMEX:IYC', displayName: 'IYC - iShares U.S. Consumer Discretionary ETF' },
                { name: 'AMEX:IYM', displayName: 'IYM - iShares U.S. Basic Materials ETF' },
                { name: 'AMEX:IYR', displayName: 'IYR - iShares U.S. Real Estate ETF' },
                { name: 'AMEX:IDU', displayName: 'IDU - iShares U.S. Utilities ETF' },
            ],
        },
        {
            name: 'J.P. Morgan',
            sourceUrl: 'https://am.jpmorgan.com/',
            symbols: [
                { name: 'AMEX:JEPI', displayName: 'JEPI - JPMorgan Equity Premium Income ETF' },
                { name: 'NASDAQ:JEPQ', displayName: 'JEPQ - JPMorgan Nasdaq Equity Premium Income ETF' },
                { name: 'AMEX:JPST', displayName: 'JPST - JPMorgan Ultra-Short Income ETF' },
                { name: 'AMEX:JMUB', displayName: 'JMUB - JPMorgan Municipal ETF' },
                { name: 'AMEX:JPUS', displayName: 'JPUS - JPMorgan Diversified Return U.S. Equity ETF' },
                { name: 'AMEX:JCPB', displayName: 'JCPB - JPMorgan Core Plus Bond ETF' },
                { name: 'AMEX:JPIE', displayName: 'JPIE - JPMorgan Income ETF' },
                { name: 'AMEX:JPLD', displayName: 'JPLD - JPMorgan U.S. Value Factor ETF' },
            ],
        },
        {
            name: 'Invesco',
            sourceUrl: 'https://www.invesco.com/',
            symbols: [
                { name: 'NASDAQ:PTF', displayName: 'PTF - Invesco DWA Technology Momentum ETF' },
                { name: 'NASDAQ:PFI', displayName: 'PFI - Invesco DWA Financial Momentum ETF' },
                { name: 'AMEX:PXE', displayName: 'PXE - Invesco DWA Energy Momentum ETF' },
                { name: 'NASDAQ:PTH', displayName: 'PTH - Invesco DWA Healthcare Momentum ETF' },
                { name: 'NASDAQ:PRN', displayName: 'PRN - Invesco DWA Industrials Momentum ETF' },
                { name: 'NASDAQ:PSL', displayName: 'PSL - Invesco DWA Consumer Staples Momentum ETF' },
                { name: 'NASDAQ:PEZ', displayName: 'PEZ - Invesco DWA Consumer Cyclicals Momentum ETF' },
                { name: 'NASDAQ:PYZ', displayName: 'PYZ - Invesco DWA Basic Materials Momentum ETF' },
                { name: 'AMEX:PSR', displayName: 'PSR - Invesco Active U.S. Real Estate ETF' },
                { name: 'NASDAQ:PUI', displayName: 'PUI - Invesco DWA Utilities Momentum ETF' },
                { name: 'NASDAQ:PXI', displayName: 'PXI - Invesco DWA Communication Services Momentum ETF' },
            ],
        },
        {
            name: 'SPDR',
            sourceUrl: 'https://www.ssga.com/us/en/intermediary/etfs',
            symbols: [
                { name: 'AMEX:XLK', displayName: 'XLK - Technology Select Sector SPDR Fund' },
                { name: 'AMEX:XLF', displayName: 'XLF - Financial Select Sector SPDR Fund' },
                { name: 'AMEX:XLE', displayName: 'XLE - Energy Select Sector SPDR Fund' },
                { name: 'AMEX:XLV', displayName: 'XLV - Health Care Select Sector SPDR Fund' },
                { name: 'AMEX:XLI', displayName: 'XLI - Industrial Select Sector SPDR Fund' },
                { name: 'AMEX:XLP', displayName: 'XLP - Consumer Staples Select Sector SPDR Fund' },
                { name: 'AMEX:XLY', displayName: 'XLY - Consumer Discretionary Select Sector SPDR Fund' },
                { name: 'AMEX:XLB', displayName: 'XLB - Materials Select Sector SPDR Fund' },
                { name: 'AMEX:XLRE', displayName: 'XLRE - Real Estate Select Sector SPDR Fund' },
                { name: 'AMEX:XLU', displayName: 'XLU - Utilities Select Sector SPDR Fund' },
                { name: 'AMEX:XLC', displayName: 'XLC - Communication Services Select Sector SPDR Fund' },
            ],
        },
        {
            name: 'Vanguard',
            sourceUrl: 'https://investor.vanguard.com/',
            symbols: [
                { name: 'AMEX:VTI', displayName: 'VTI - Vanguard Total Stock Market ETF' },
                { name: 'AMEX:VOO', displayName: 'VOO - Vanguard S&P 500 ETF' },
                { name: 'AMEX:VT', displayName: 'VT - Vanguard Total World Stock ETF' },
                { name: 'NASDAQ:VTWO', displayName: 'VTWO - Vanguard Russell 2000 ETF' },
                { name: 'NASDAQ:VXUS', displayName: 'VXUS - Vanguard Total International Stock ETF' },
                { name: 'AMEX:VEA', displayName: 'VEA - Vanguard FTSE Developed Markets ETF' },
                { name: 'AMEX:VWO', displayName: 'VWO - Vanguard FTSE Emerging Markets ETF' },
                { name: 'AMEX:VEU', displayName: 'VEU - Vanguard FTSE All-World ex-US ETF' },
                { name: 'AMEX:VGT', displayName: 'VGT - Vanguard Information Technology ETF' },
                { name: 'AMEX:VFH', displayName: 'VFH - Vanguard Financials ETF' },
                { name: 'AMEX:VDE', displayName: 'VDE - Vanguard Energy ETF' },
                { name: 'AMEX:VHT', displayName: 'VHT - Vanguard Health Care ETF' },
                { name: 'AMEX:VIS', displayName: 'VIS - Vanguard Industrials ETF' },
                { name: 'AMEX:VDC', displayName: 'VDC - Vanguard Consumer Staples ETF' },
                { name: 'AMEX:VCR', displayName: 'VCR - Vanguard Consumer Discretionary ETF' },
                { name: 'AMEX:VAW', displayName: 'VAW - Vanguard Materials ETF' },
                { name: 'AMEX:VNQ', displayName: 'VNQ - Vanguard Real Estate ETF' },
                { name: 'AMEX:VPU', displayName: 'VPU - Vanguard Utilities ETF' },
                { name: 'AMEX:VOX', displayName: 'VOX - Vanguard Communication Services ETF' },
            ],
        },
    ],
};
